import { useEffect, useMemo, useRef, useState } from 'react';

const wrap = (text, start, end, before, after = before) => `${text.slice(0, start)}${before}${text.slice(start, end) || 'texto'}${after}${text.slice(end)}`;
const lines = (text, start, end, prefix) => `${text.slice(0, start)}${text.slice(start, end).split('\n').map((line) => `${prefix}${line}`).join('\n')}${text.slice(end)}`;

export default function RichNewsEditor({ value, onChange, draftKey = 'news' }) {
  const ref = useRef(null); const [preview, setPreview] = useState(false); const [device, setDevice] = useState('desktop'); const [saved, setSaved] = useState('');
  const stats = useMemo(() => { const words = String(value).trim().split(/\s+/).filter(Boolean).length; return { words, minutes: Math.max(1, Math.ceil(words / 220)) }; }, [value]);
  useEffect(() => { const timer = setTimeout(() => { try { localStorage.setItem(`nw3-draft:${draftKey}`, value); setSaved(new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })); } catch {} }, 800); return () => clearTimeout(timer); }, [value, draftKey]);
  const apply = (kind) => { const input = ref.current; const start = input.selectionStart, end = input.selectionEnd; let next = value; if (kind === 'bold') next = wrap(value,start,end,'**'); if (kind === 'italic') next = wrap(value,start,end,'*'); if (kind === 'underline') next = wrap(value,start,end,'<u>','</u>'); if (kind === 'h1') next = lines(value,start,end,'# '); if (kind === 'h2') next = lines(value,start,end,'## '); if (kind === 'ul') next = lines(value,start,end,'- '); if (kind === 'ol') next = lines(value,start,end,'1. '); if (kind === 'quote') next = lines(value,start,end,'> '); if (kind === 'link') { const url = prompt('Enlace HTTPS'); if (url?.startsWith('https://')) next = wrap(value,start,end,'[',`](${url})`); } onChange(next); requestAnimationFrame(() => input.focus()); };
  return <div className="rich-news-editor"><div className="rich-news-toolbar" role="toolbar" aria-label="Formato del artículo">{[['h1','Título'],['h2','Subtítulo'],['bold','B'],['italic','I'],['underline','U'],['ul','• Lista'],['ol','1. Lista'],['quote','❝'],['link','🔗']].map(([kind,label])=><button key={kind} type="button" onClick={()=>apply(kind)} title={label}>{label}</button>)}<button type="button" onClick={()=>document.execCommand('undo')}>↶</button><button type="button" onClick={()=>document.execCommand('redo')}>↷</button><span className="rich-news-spacer"/><button type="button" className={device==='desktop'?'active':''} onClick={()=>setDevice('desktop')}>Escritorio</button><button type="button" className={device==='mobile'?'active':''} onClick={()=>setDevice('mobile')}>Móvil</button><button type="button" className={preview?'active':''} onClick={()=>setPreview(!preview)}>Vista previa</button></div>{preview?<div className={`rich-news-document rich-news-document--${device}`}>{String(value).split(/\n\s*\n/).filter(Boolean).map((paragraph,index)=><p key={index}>{paragraph}</p>)}</div>:<textarea ref={ref} name="contenido" rows={18} maxLength={40000} required value={value} onChange={(event)=>onChange(event.target.value)} spellCheck="true"/>}<footer><span>{stats.words} palabras · {stats.minutes} min de lectura</span><span>{saved ? `Borrador guardado ${saved}` : 'Autoguardado activo'}</span></footer></div>;
}
