import React, { useEffect, useState } from 'react';
import { AlertTriangle, BellRing, CheckCircle2, Clock3, RefreshCw } from 'lucide-react';
import { toast } from 'sonner';
import apiServerClient from '@/lib/apiServerClient.js';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';

const AccountIncidentCenterPanel = () => {
  const [data, setData] = useState({ incidents: [], summary: {} }); const [busy, setBusy] = useState('');
  const load = async () => { const response = await apiServerClient.fetch('/moonbot-admin/account-tools/incidents'); const body = await apiServerClient.readJson(response); if (!response.ok) throw new Error(body.error); setData(body); };
  useEffect(() => { load().catch(() => setData({ incidents: [], summary: {} })); }, []);
  const action = async (incidentId, name, hours) => { setBusy(incidentId); try { const response = await apiServerClient.fetch('/moonbot-admin/account-tools/incidents', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ incident_id: incidentId, action: name, hours }) }); const body = await apiServerClient.readJson(response); if (!response.ok) throw new Error(body.error); await load(); toast.success('Incidencia actualizada'); } catch (error) { toast.error(error.message); } finally { setBusy(''); } };
  const visible = data.incidents.filter((item) => item.status !== 'resolved');
  return <section className="space-y-4 rounded-xl border bg-background p-4 xl:col-span-2"><div className="flex items-start justify-between gap-3"><div><h3 className="flex items-center gap-2 font-semibold"><BellRing className="h-4 w-4"/>Centro de incidencias correlacionadas</h3><p className="text-xs text-muted-foreground">Agrupa señales de una misma cuenta, calcula su prioridad y asigna un plazo de revisión. No ejecuta sanciones automáticas.</p></div><Button size="icon" variant="ghost" title="Actualizar" onClick={() => load().catch((error) => toast.error(error.message))}><RefreshCw className="h-4 w-4"/></Button></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><div className="rounded-lg border p-3"><b className="text-xl">{data.summary.total || 0}</b><small className="block text-muted-foreground">Correlacionadas</small></div><div className="rounded-lg border p-3"><b className="text-xl">{data.summary.open || 0}</b><small className="block text-muted-foreground">Sin revisar</small></div><div className="rounded-lg border p-3"><b className="text-xl text-destructive">{data.summary.critical || 0}</b><small className="block text-muted-foreground">Críticas</small></div><div className="rounded-lg border p-3"><b className="text-xl">{data.summary.acknowledged || 0}</b><small className="block text-muted-foreground">Reconocidas</small></div></div><div className="space-y-2">{visible.slice(0, 12).map((item) => <div key={item.id} className="rounded-lg border p-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><span className="flex items-center gap-2"><AlertTriangle className={`h-4 w-4 ${item.severity === 'critical' ? 'text-destructive' : 'text-amber-600'}`}/><b>Cuenta {item.account_id}</b><Badge variant={item.severity === 'critical' ? 'destructive' : 'outline'}>{item.severity}</Badge><Badge variant="secondary">{item.correlated_signals} señales</Badge></span><small className="text-muted-foreground"><Clock3 className="mr-1 inline h-3 w-3"/>SLA {item.escalation.sla_minutes} min · {item.escalation.target_role}</small></div><ul className="my-2 list-inside list-disc text-xs text-muted-foreground">{item.causes.map((cause, index) => <li key={`${cause.type}-${index}`}>{cause.explanation}</li>)}</ul><div className="flex flex-wrap gap-2">{item.status === 'open' && <Button size="sm" variant="outline" disabled={busy === item.id} onClick={() => action(item.id, 'acknowledge')}>Reconocer</Button>}<Button size="sm" variant="outline" disabled={busy === item.id} onClick={() => action(item.id, 'snooze', 4)}>Posponer 4 h</Button><Button size="sm" disabled={busy === item.id} onClick={() => action(item.id, 'resolve')}><CheckCircle2 className="mr-1 h-4 w-4"/>Resolver</Button></div></div>)}{!visible.length && <p className="rounded-lg border border-emerald-500/30 bg-emerald-500/5 p-3 text-sm text-emerald-700">No hay incidencias activas que requieran intervención.</p>}</div></section>;
};
export default AccountIncidentCenterPanel;
