import React, { useEffect, useMemo, useState } from 'react';
import { Download, FlaskConical, Search, Settings2, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Badge } from '@/components/ui/badge';
import apiServerClient from '@/lib/apiServerClient'; import pb from '@/lib/pocketbaseClient';
import AccountDelegationsPanel from '@/components/AccountDelegationsPanel.jsx';
import AccountIncidentCenterPanel from '@/components/AccountIncidentCenterPanel.jsx';

const AccountHorizonTools = ({ users, proxies, onRefresh }) => {
  const [query, setQuery] = useState(''); const [role, setRole] = useState('user'); const [includeFrozen, setIncludeFrozen] = useState(false);
  const [history, setHistory] = useState([]);
  const [anomalies, setAnomalies] = useState([]);
  const [recommendations, setRecommendations] = useState([]);
  const [guidance, setGuidance] = useState([]);
  const [reportSchedules, setReportSchedules] = useState([]);
  const [reportDraft, setReportDraft] = useState({ frequency: 'weekly', timezone: 'Europe/Madrid', format: 'json', time: '09:00', weekday: 1, day_of_month: 1, recipients: pb.authStore.record?.email || '' });
  const [reviewAt, setReviewAt] = useState(() => localStorage.getItem('account_review_at') || '');
  const [targetRole, setTargetRole] = useState('user'); const [lastTransaction, setLastTransaction] = useState(null);
  const [recovery, setRecovery] = useState({ event: null, fields: [], preview: null, busy: false });
  const [rule, setRule] = useState(() => JSON.parse(localStorage.getItem('account_horizon_rule') || '{"inactiveProxies":5,"frozenAccounts":1}'));
  const normalized = (value) => String(value || '').toLocaleLowerCase('es').normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  const results = useMemo(() => { const terms = normalized(query).split(/\s+/).filter(Boolean); if (!terms.length) return [];
    return users.map((user) => { const text = normalized(`${user.name} ${user.email} ${user.role} ${user.is_frozen ? 'congelada bloqueada' : 'activa'}`); return { user, score: terms.reduce((score, term) => score + (text.includes(term) ? 2 : 0) + (normalized(user.role) === term ? 2 : 0), 0) }; }).filter((row) => row.score).sort((a, b) => b.score - a.score).slice(0, 8); }, [users, query]);
  const simulation = users.filter((user) => user.role === role && (includeFrozen || !user.is_frozen));
  const saveRule = () => { localStorage.setItem('account_horizon_rule', JSON.stringify(rule)); };
  const exportSigned = async () => { const payload = { exported_at: new Date().toISOString(), summary: { users: users.length, proxies: proxies.length }, accounts: users.map(({ id, role, created, updated, is_frozen }) => ({ id, role, created, updated, is_frozen })) }; const response = await apiServerClient.fetch('/moonbot-admin/account-tools/sign', { method: 'POST', headers: { Authorization: `Bearer ${pb.authStore.token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ payload }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); const blob = new Blob([JSON.stringify(data.bundle, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `accounts-signed-${Date.now()}.json`; link.click(); URL.revokeObjectURL(url); };
  const inactive = proxies.filter((item) => item.status !== 'active').length; const frozen = users.filter((item) => item.is_frozen).length;
  const bulk = async (operation) => { if (operation === 'apply' && !confirm(`Cambiar ${simulation.length} cuentas a ${targetRole}?`)) return; const response = await apiServerClient.fetch('/moonbot-admin/account-tools/bulk', { method: 'POST', headers: { Authorization: `Bearer ${pb.authStore.token}`, 'Content-Type': 'application/json' }, body: JSON.stringify(operation === 'undo' ? { operation, transaction_id: lastTransaction?.id } : { operation, account_ids: simulation.map((user) => user.id), role: targetRole }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setLastTransaction(operation === 'undo' ? null : data.transaction); };
  const recover = async (preview) => { setRecovery((value) => ({ ...value, busy: true, error: '' })); try { const response = await apiServerClient.fetch('/moonbot-admin/account-tools/recover', { method: 'POST', headers: { Authorization: `Bearer ${pb.authStore.token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ event_id: recovery.event?.id, fields: recovery.fields, preview, actor_id: pb.authStore.record?.id }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); if (preview) setRecovery((value) => ({ ...value, preview: data.preview, busy: false })); else { setRecovery({ event: null, fields: [], preview: null, busy: false }); await onRefresh?.(); const refreshed = await apiServerClient.fetch('/moonbot-admin/account-tools/history', { headers: { Authorization: `Bearer ${pb.authStore.token}` } }); const historyData = await refreshed.json(); setHistory(historyData.history || []); } } catch (error) { setRecovery((value) => ({ ...value, busy: false, error: error.message })); } };
  useEffect(() => { apiServerClient.fetch('/moonbot-admin/account-tools/history', { headers: { Authorization: `Bearer ${pb.authStore.token}` } }).then((response) => response.json()).then((data) => setHistory(data.history || [])).catch(() => {}); }, [users]);
  useEffect(() => { apiServerClient.fetch('/moonbot-admin/account-tools/anomalies', { headers: { Authorization: `Bearer ${pb.authStore.token}` } }).then((response) => response.json()).then((data) => setAnomalies(data.anomalies || [])).catch(() => {}); }, [users, proxies]);
  useEffect(() => { apiServerClient.fetch('/moonbot-admin/account-tools/recommendations', { headers: { Authorization: `Bearer ${pb.authStore.token}` } }).then((response) => response.json()).then((data) => setRecommendations(data.recommendations || [])).catch(() => {}); }, [users, proxies]);
  useEffect(() => { apiServerClient.fetch('/moonbot-admin/account-tools/guidance', { headers: { Authorization: `Bearer ${pb.authStore.token}` } }).then((response) => response.json()).then((data) => setGuidance(data.steps || [])).catch(() => {}); }, [users, proxies]);
  const loadReportSchedules = () => apiServerClient.fetch('/moonbot-admin/account-tools/reports', { headers: { Authorization: `Bearer ${pb.authStore.token}` } }).then((response) => response.json()).then((data) => setReportSchedules(data.schedules || [])).catch(() => {});
  useEffect(() => { loadReportSchedules(); }, []);
  const reportAction = async (action, scheduleId, enabled) => { const payload = action === 'save' ? { action, schedule: { ...reportDraft, recipients: reportDraft.recipients.split(',').map((item) => item.trim()).filter(Boolean), weekday: Number(reportDraft.weekday), day_of_month: Number(reportDraft.day_of_month) } } : { action, schedule_id: scheduleId, enabled }; const response = await apiServerClient.fetch('/moonbot-admin/account-tools/reports', { method: 'POST', headers: { Authorization: `Bearer ${pb.authStore.token}`, 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); await loadReportSchedules(); };
  const downloadReport = async (filename) => { const response = await apiServerClient.fetch(`/moonbot-admin/account-tools/reports/${encodeURIComponent(filename)}`, { headers: { Authorization: `Bearer ${pb.authStore.token}` } }); if (!response.ok) throw new Error('No se pudo descargar el informe'); const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); };
  return <div className="grid gap-4 xl:grid-cols-2">
    <AccountIncidentCenterPanel />
    {pb.authStore.record?.role === 'creator' && <AccountDelegationsPanel users={users}/>}
    <section className="space-y-3 rounded-xl border bg-background p-4 xl:col-span-2"><h3 className="flex items-center gap-2 font-semibold"><Sparkles className="h-4 w-4"/>Asistente guiado de cuentas</h3>{guidance.slice(0, 8).map((step) => <div key={step.id} className="rounded-lg border p-2 text-xs"><div className="flex justify-between gap-2"><b>{step.action.replaceAll('_', ' ')}</b><Badge variant="outline">{step.priority}</Badge></div><p className="text-muted-foreground">{step.explanation}</p><small>Origen: {step.source} · confirmación manual obligatoria</small></div>)}{!guidance.length && <p className="text-sm text-muted-foreground">No hay pasos pendientes. El asistente explica y prioriza, pero nunca aplica cambios automáticamente.</p>}</section>
    <section className="space-y-3 rounded-xl border bg-background p-4"><h3 className="flex items-center gap-2 font-semibold"><Settings2 className="h-4 w-4"/>Automatización configurable</h3><label className="text-sm">Alertar desde proxies inactivos<Input type="number" min="0" value={rule.inactiveProxies} onChange={(e) => setRule({ ...rule, inactiveProxies: Number(e.target.value) })}/></label><label className="text-sm">Alertar desde cuentas congeladas<Input type="number" min="0" value={rule.frozenAccounts} onChange={(e) => setRule({ ...rule, frozenAccounts: Number(e.target.value) })}/></label><div className="flex gap-2"><Button size="sm" onClick={saveRule}>Guardar regla</Button><Button size="sm" variant="outline" onClick={() => setRule({ inactiveProxies: 1, frozenAccounts: 1 })}>Plantilla estricta</Button><Button size="sm" variant="outline" onClick={() => setRule({ inactiveProxies: 10, frozenAccounts: 5 })}>Plantilla flexible</Button></div><p className="text-xs text-muted-foreground">Estado: {inactive >= rule.inactiveProxies || frozen >= rule.frozenAccounts ? 'requiere atención' : 'dentro de los límites'}.</p></section>
    <section className="space-y-3 rounded-xl border bg-background p-4"><h3 className="flex items-center gap-2 font-semibold"><Sparkles className="h-4 w-4"/>Anomalías explicables</h3>{anomalies.slice(0, 8).map((item) => <div key={item.id} className="rounded-lg border p-2 text-xs"><div className="flex justify-between gap-2"><b>{item.severity === 'critical' ? 'Crítica' : 'Alta'} · {item.type.replaceAll('_', ' ')}</b><Badge variant={item.severity === 'critical' ? 'destructive' : 'outline'}>{item.account_ids?.length || 0} cuenta(s)</Badge></div><p className="text-muted-foreground">{item.explanation}</p></div>)}{!anomalies.length && <p className="text-sm text-muted-foreground">No se detectan identidades duplicadas, privilegios incoherentes ni concentraciones anómalas de proxies.</p>}</section>
    <section className="space-y-3 rounded-xl border bg-background p-4"><h3 className="flex items-center gap-2 font-semibold"><Sparkles className="h-4 w-4"/>Recomendaciones personalizadas</h3>{recommendations.filter((item) => item.action !== 'maintain').slice(0, 8).map((item) => <div key={item.account_id} className="rounded-lg border p-2 text-xs"><div className="flex justify-between"><b>{item.action.replaceAll('_', ' ')}</b><Badge variant="outline">{item.priority} · {item.score}</Badge></div><p className="text-muted-foreground">{item.explanation}</p><small>Cuenta {item.account_id} · requiere revisión manual</small></div>)}{!recommendations.some((item) => item.action !== 'maintain') && <p className="text-sm text-muted-foreground">No hay recomendaciones prioritarias. El motor no ejecuta acciones automáticamente.</p>}</section>
    <section className="space-y-3 rounded-xl border bg-background p-4"><h3 className="flex items-center gap-2 font-semibold"><FlaskConical className="h-4 w-4"/>Simulador y acción masiva reversible</h3><select className="h-10 w-full rounded-md border bg-background px-3" value={role} onChange={(e) => setRole(e.target.value)}>{['user','moderator','admin','creator'].map((x) => <option key={x}>{x}</option>)}</select><label className="flex justify-between text-sm">Incluir congeladas<input type="checkbox" checked={includeFrozen} onChange={(e) => setIncludeFrozen(e.target.checked)}/></label><p className="text-sm"><b>{simulation.length}</b> cuentas quedarían afectadas.</p><select className="h-10 w-full rounded-md border bg-background px-3" value={targetRole} onChange={(e) => setTargetRole(e.target.value)}>{['user','moderator','admin'].map((x) => <option key={x}>{x}</option>)}</select><div className="flex gap-2"><Button size="sm" onClick={() => bulk('apply').catch(() => {})}>Aplicar con registro</Button>{lastTransaction && <Button size="sm" variant="outline" onClick={() => bulk('undo').catch(() => {})}>Deshacer</Button>}</div></section>
    <section className="space-y-3 rounded-xl border bg-background p-4"><h3 className="flex items-center gap-2 font-semibold"><Search className="h-4 w-4"/>Búsqueda por significado</h3><Input placeholder="Ej.: administradores activos" value={query} onChange={(e) => setQuery(e.target.value)}/><div className="flex flex-wrap gap-2">{results.map(({ user, score }) => <Badge key={user.id} variant="outline">{user.name || user.email} · {score}</Badge>)}</div></section>
    <section className="space-y-3 rounded-xl border bg-background p-4"><h3 className="flex items-center gap-2 font-semibold"><Sparkles className="h-4 w-4"/>Resumen explicable y exportación</h3><p className="text-sm">Hay {users.length} cuentas, {frozen} congeladas y {inactive} proxies no activos. La alerta se activa comparando estos valores con los límites configurados.</p><Button size="sm" variant="outline" onClick={() => exportSigned().catch(() => {})}><Download className="mr-2 h-4 w-4"/>Exportar paquete firmado</Button></section>
    <section className="space-y-2 rounded-xl border bg-background p-4 xl:col-span-2"><h3 className="font-semibold">Historial versionado y recuperación selectiva</h3>{history.slice(0, 8).map((item) => { const fields = ['role', 'is_frozen'].filter((field) => Object.hasOwn(item.before || {}, field)); return <div key={item.id} className="rounded-lg bg-muted/30 p-2 text-xs"><div className="flex flex-wrap items-center justify-between gap-2"><span>{item.action} · {item.account_id}</span><span>{new Date(item.created_at).toLocaleString()}</span></div>{fields.length > 0 && item.action !== 'recovery' && <Button size="sm" variant="ghost" className="mt-1" onClick={() => setRecovery({ event: item, fields, preview: null, busy: false })}>Recuperar campos…</Button>}</div>; })}{!history.length && <p className="text-sm text-muted-foreground">Los próximos cambios de rol, congelación y borrado aparecerán aquí.</p>}{recovery.event && <div className="space-y-2 rounded-lg border border-primary/30 p-3"><b>Recuperar cuenta {recovery.event.account_id}</b><div className="flex flex-wrap gap-3">{['role', 'is_frozen'].filter((field) => Object.hasOwn(recovery.event.before || {}, field)).map((field) => <label key={field} className="flex items-center gap-2"><input type="checkbox" checked={recovery.fields.includes(field)} onChange={(event) => setRecovery((value) => ({ ...value, preview: null, fields: event.target.checked ? [...value.fields, field] : value.fields.filter((item) => item !== field) }))}/>{field === 'role' ? 'Rol' : 'Estado congelado'}</label>)}</div>{recovery.preview && <pre className="overflow-auto rounded bg-muted p-2">{JSON.stringify(recovery.preview, null, 2)}</pre>}{recovery.error && <p className="text-destructive">{recovery.error}</p>}<div className="flex gap-2"><Button size="sm" disabled={recovery.busy || !recovery.fields.length} onClick={() => recover(true)}>Vista previa</Button><Button size="sm" disabled={recovery.busy || !recovery.preview} onClick={() => recover(false)}>Confirmar recuperación</Button><Button size="sm" variant="outline" onClick={() => setRecovery({ event: null, fields: [], preview: null, busy: false })}>Cancelar</Button></div></div>}</section>
    <section className="space-y-2 rounded-xl border bg-background p-4 xl:col-span-2"><h3 className="font-semibold">Calendario inteligente de revisión</h3><div className="flex gap-2"><Input type="datetime-local" value={reviewAt} onChange={(e) => setReviewAt(e.target.value)}/><Button onClick={() => localStorage.setItem('account_review_at', reviewAt)}>Programar</Button></div><p className="text-xs text-muted-foreground">{reviewAt ? `Próxima revisión: ${new Date(reviewAt).toLocaleString()}` : 'No hay revisión programada.'}</p></section>
    <section className="space-y-3 rounded-xl border bg-background p-4 xl:col-span-2"><h3 className="font-semibold">Informes programados de cuentas</h3><div className="grid gap-2 md:grid-cols-3"><select className="h-10 rounded border bg-background px-2" value={reportDraft.frequency} onChange={(event) => setReportDraft({ ...reportDraft, frequency: event.target.value })}><option value="daily">Diario</option><option value="weekly">Semanal</option><option value="monthly">Mensual</option></select><Input type="time" value={reportDraft.time} onChange={(event) => setReportDraft({ ...reportDraft, time: event.target.value })}/><select className="h-10 rounded border bg-background px-2" value={reportDraft.format} onChange={(event) => setReportDraft({ ...reportDraft, format: event.target.value })}><option value="json">JSON</option><option value="csv">CSV</option></select>{reportDraft.frequency === 'weekly' && <Input type="number" min="1" max="7" value={reportDraft.weekday} onChange={(event) => setReportDraft({ ...reportDraft, weekday: event.target.value })}/>} {reportDraft.frequency === 'monthly' && <Input type="number" min="1" max="28" value={reportDraft.day_of_month} onChange={(event) => setReportDraft({ ...reportDraft, day_of_month: event.target.value })}/>}<Input value={reportDraft.timezone} onChange={(event) => setReportDraft({ ...reportDraft, timezone: event.target.value })} placeholder="Europe/Madrid"/><Input value={reportDraft.recipients} onChange={(event) => setReportDraft({ ...reportDraft, recipients: event.target.value })} placeholder="Correos, separados por coma"/></div><Button size="sm" onClick={() => reportAction('save').catch((error) => alert(error.message))}>Programar informe</Button>{reportSchedules.map((schedule) => <div key={schedule.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border p-2 text-xs"><span><b>{schedule.frequency} · {schedule.format.toUpperCase()}</b><small className="block">Próxima ejecución: {new Date(schedule.next_run).toLocaleString()}</small></span><span className="flex gap-2"><Button size="sm" variant="outline" onClick={() => reportAction('run_now', schedule.id).catch((error) => alert(error.message))}>Generar ahora</Button><Button size="sm" variant="outline" onClick={() => reportAction('toggle', schedule.id, !schedule.enabled).catch((error) => alert(error.message))}>{schedule.enabled ? 'Pausar' : 'Activar'}</Button>{schedule.last_report?.filename && <Button size="sm" onClick={() => downloadReport(schedule.last_report.filename).catch((error) => alert(error.message))}>Descargar</Button>}</span></div>)}</section>
  </div>;
}; export default AccountHorizonTools;
