import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { CalendarClock, Search, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import apiServerClient from '@/lib/apiServerClient';
import pb from '@/lib/pocketbaseClient';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

const AccountSearchReviewPanel = ({ users }) => {
  const [query, setQuery] = useState('');
  const [results, setResults] = useState([]);
  const [schedules, setSchedules] = useState([]);
  const [selected, setSelected] = useState([]);
  const [busy, setBusy] = useState(false);
  const [draft, setDraft] = useState({ frequency: 'weekly', priority: 'medium', timezone: 'Europe/Madrid', time: '09:00', weekday: 1, day_of_month: 1 });
  const headers = { Authorization: `Bearer ${pb.authStore.token}`, 'Content-Type': 'application/json' };
  const usersById = useMemo(() => new Map(users.map((item) => [item.id, item])), [users]);
  const loadSchedules = useCallback(async () => { const response = await apiServerClient.fetch('/moonbot-admin/account-tools/reviews', { headers }); const data = await response.json(); if (response.ok) setSchedules(data.schedules || []); }, []);
  useEffect(() => { loadSchedules().catch(() => {}); }, [loadSchedules]);
  const search = async () => { setBusy(true); try { const response = await apiServerClient.fetch(`/moonbot-admin/account-tools/semantic-search?q=${encodeURIComponent(query)}`, { headers }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setResults(data.results || []); } catch (error) { toast.error(error.message); } finally { setBusy(false); } };
  const reviewAction = async (payload, message) => { setBusy(true); try { const response = await apiServerClient.fetch('/moonbot-admin/account-tools/reviews', { method: 'POST', headers, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setSchedules(data.schedules || []); toast.success(message); } catch (error) { toast.error(error.message); } finally { setBusy(false); } };
  const create = () => reviewAction({ action: 'create', schedule: { ...draft, account_ids: selected, weekday: Number(draft.weekday), day_of_month: Number(draft.day_of_month) } }, 'Revisión programada');
  const toggleSelected = (id) => setSelected((value) => value.includes(id) ? value.filter((item) => item !== id) : [...value, id]);
  return <section className="grid gap-4 rounded-xl border bg-background p-4 xl:grid-cols-2">
    <div className="space-y-3"><h3 className="flex items-center gap-2 font-semibold"><Search className="h-4 w-4" />Búsqueda semántica explicable</h3><div className="flex gap-2"><Input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && search()} placeholder="Ej.: administradores activos sin proxy" /><Button disabled={busy || !query.trim()} onClick={search}>Buscar</Button></div><p className="text-xs text-muted-foreground">Interpreta intención, roles, estado, verificación y proxies sin enviar datos a servicios externos.</p><div className="space-y-2">{results.map((result) => { const account = usersById.get(result.account_id); return <label key={result.account_id} className="flex cursor-pointer items-start gap-3 rounded-lg border p-3"><input className="mt-1" type="checkbox" checked={selected.includes(result.account_id)} onChange={() => toggleSelected(result.account_id)} /><span className="min-w-0"><b className="block truncate">{account?.name || account?.email || result.account_id}</b><small className="text-muted-foreground">{result.explanation} Puntuación {result.score}.</small></span></label>; })}{query && !results.length && <p className="text-sm text-muted-foreground">No hay coincidencias para esta intención.</p>}</div></div>
    <div className="space-y-3"><h3 className="flex items-center gap-2 font-semibold"><CalendarClock className="h-4 w-4" />Calendario inteligente de revisiones</h3><p className="text-xs text-muted-foreground">Programa revisiones pasivas con zona horaria y recurrencia. No modifica cuentas automáticamente.</p><div className="grid gap-2 sm:grid-cols-2"><select className="h-10 rounded border bg-background px-2" value={draft.frequency} onChange={(event) => setDraft({ ...draft, frequency: event.target.value })}><option value="daily">Diaria</option><option value="weekly">Semanal</option><option value="monthly">Mensual</option></select><select className="h-10 rounded border bg-background px-2" value={draft.priority} onChange={(event) => setDraft({ ...draft, priority: event.target.value })}>{['low', 'medium', 'high', 'critical'].map((item) => <option key={item}>{item}</option>)}</select><Input type="time" value={draft.time} onChange={(event) => setDraft({ ...draft, time: event.target.value })} /><Input value={draft.timezone} onChange={(event) => setDraft({ ...draft, timezone: event.target.value })} placeholder="Europe/Madrid" />{draft.frequency === 'weekly' && <Input type="number" min="1" max="7" value={draft.weekday} onChange={(event) => setDraft({ ...draft, weekday: event.target.value })} />}{draft.frequency === 'monthly' && <Input type="number" min="1" max="28" value={draft.day_of_month} onChange={(event) => setDraft({ ...draft, day_of_month: event.target.value })} />}</div><Button size="sm" disabled={busy || !selected.length} onClick={create}>Programar {selected.length} cuenta(s)</Button><div className="space-y-2">{schedules.map((item) => <div key={item.id} className="flex items-center justify-between gap-2 rounded-lg border p-3 text-sm"><span><b>{item.frequency} · {item.priority}</b><small className="block text-muted-foreground">{item.account_ids.length} cuentas · {new Date(item.next_run).toLocaleString()}</small></span><span className="flex gap-1"><Badge variant={item.enabled ? 'default' : 'secondary'}>{item.enabled ? 'Activa' : 'Pausada'}</Badge><Button size="sm" variant="outline" onClick={() => reviewAction({ action: 'toggle', schedule_id: item.id, enabled: !item.enabled }, item.enabled ? 'Revisión pausada' : 'Revisión activada')}>{item.enabled ? 'Pausar' : 'Activar'}</Button><Button size="icon" variant="ghost" title="Eliminar" onClick={() => confirm('¿Eliminar esta revisión?') && reviewAction({ action: 'delete', schedule_id: item.id }, 'Revisión eliminada')}><Trash2 className="h-4 w-4" /></Button></span></div>)}</div></div>
  </section>;
};

export default AccountSearchReviewPanel;
