import React, { useEffect, useMemo, useState } from 'react';
import { Download, FlaskConical, Search, Settings2, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Badge } from '@/components/ui/badge';
import apiServerClient from '@/lib/apiServerClient'; import pb from '@/lib/pocketbaseClient';

const AccountHorizonTools = ({ users, proxies }) => {
  const [query, setQuery] = useState(''); const [role, setRole] = useState('user'); const [includeFrozen, setIncludeFrozen] = useState(false);
  const [history, setHistory] = useState([]);
  const [rule, setRule] = useState(() => JSON.parse(localStorage.getItem('account_horizon_rule') || '{"inactiveProxies":5,"frozenAccounts":1}'));
  const normalized = (value) => String(value || '').toLocaleLowerCase('es').normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  const results = useMemo(() => { const terms = normalized(query).split(/\s+/).filter(Boolean); if (!terms.length) return [];
    return users.map((user) => { const text = normalized(`${user.name} ${user.email} ${user.role} ${user.is_frozen ? 'congelada bloqueada' : 'activa'}`); return { user, score: terms.reduce((score, term) => score + (text.includes(term) ? 2 : 0) + (normalized(user.role) === term ? 2 : 0), 0) }; }).filter((row) => row.score).sort((a, b) => b.score - a.score).slice(0, 8); }, [users, query]);
  const simulation = users.filter((user) => user.role === role && (includeFrozen || !user.is_frozen));
  const saveRule = () => { localStorage.setItem('account_horizon_rule', JSON.stringify(rule)); };
  const exportSigned = async () => { const payload = { exported_at: new Date().toISOString(), summary: { users: users.length, proxies: proxies.length }, accounts: users.map(({ id, role, created, updated, is_frozen }) => ({ id, role, created, updated, is_frozen })) }; const response = await apiServerClient.fetch('/moonbot-admin/account-tools/sign', { method: 'POST', headers: { Authorization: `Bearer ${pb.authStore.token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ payload }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); const blob = new Blob([JSON.stringify(data.bundle, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `accounts-signed-${Date.now()}.json`; link.click(); URL.revokeObjectURL(url); };
  const inactive = proxies.filter((item) => item.status !== 'active').length; const frozen = users.filter((item) => item.is_frozen).length;
  useEffect(() => { apiServerClient.fetch('/moonbot-admin/account-tools/history', { headers: { Authorization: `Bearer ${pb.authStore.token}` } }).then((response) => response.json()).then((data) => setHistory(data.history || [])).catch(() => {}); }, [users]);
  return <div className="grid gap-4 xl:grid-cols-2">
    <section className="space-y-3 rounded-xl border bg-background p-4"><h3 className="flex items-center gap-2 font-semibold"><Settings2 className="h-4 w-4"/>Automatización configurable</h3><label className="text-sm">Alertar desde proxies inactivos<Input type="number" min="0" value={rule.inactiveProxies} onChange={(e) => setRule({ ...rule, inactiveProxies: Number(e.target.value) })}/></label><label className="text-sm">Alertar desde cuentas congeladas<Input type="number" min="0" value={rule.frozenAccounts} onChange={(e) => setRule({ ...rule, frozenAccounts: Number(e.target.value) })}/></label><Button size="sm" onClick={saveRule}>Guardar regla</Button><p className="text-xs text-muted-foreground">Estado: {inactive >= rule.inactiveProxies || frozen >= rule.frozenAccounts ? 'requiere atención' : 'dentro de los límites'}.</p></section>
    <section className="space-y-3 rounded-xl border bg-background p-4"><h3 className="flex items-center gap-2 font-semibold"><FlaskConical className="h-4 w-4"/>Simulador previo</h3><select className="h-10 w-full rounded-md border bg-background px-3" value={role} onChange={(e) => setRole(e.target.value)}>{['user','moderator','admin','creator'].map((x) => <option key={x}>{x}</option>)}</select><label className="flex justify-between text-sm">Incluir congeladas<input type="checkbox" checked={includeFrozen} onChange={(e) => setIncludeFrozen(e.target.checked)}/></label><p className="text-sm"><b>{simulation.length}</b> cuentas quedarían afectadas. No se ha modificado ninguna.</p></section>
    <section className="space-y-3 rounded-xl border bg-background p-4"><h3 className="flex items-center gap-2 font-semibold"><Search className="h-4 w-4"/>Búsqueda por significado</h3><Input placeholder="Ej.: administradores activos" value={query} onChange={(e) => setQuery(e.target.value)}/><div className="flex flex-wrap gap-2">{results.map(({ user, score }) => <Badge key={user.id} variant="outline">{user.name || user.email} · {score}</Badge>)}</div></section>
    <section className="space-y-3 rounded-xl border bg-background p-4"><h3 className="flex items-center gap-2 font-semibold"><Sparkles className="h-4 w-4"/>Resumen explicable y exportación</h3><p className="text-sm">Hay {users.length} cuentas, {frozen} congeladas y {inactive} proxies no activos. La alerta se activa comparando estos valores con los límites configurados.</p><Button size="sm" variant="outline" onClick={() => exportSigned().catch(() => {})}><Download className="mr-2 h-4 w-4"/>Exportar paquete firmado</Button></section>
    <section className="space-y-2 rounded-xl border bg-background p-4 xl:col-span-2"><h3 className="font-semibold">Historial versionado persistente</h3>{history.slice(0, 8).map((item) => <div key={item.id} className="flex justify-between rounded-lg bg-muted/30 p-2 text-xs"><span>{item.action} · {item.account_id}</span><span>{new Date(item.created_at).toLocaleString()}</span></div>)}{!history.length && <p className="text-sm text-muted-foreground">Los próximos cambios de rol, congelación y borrado aparecerán aquí.</p>}</section>
  </div>;
}; export default AccountHorizonTools;
