import React, { useEffect, useMemo, useState } from 'react';
import { Bell, CalendarClock, CheckSquare, MessageSquare, Tags, UserRound } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import apiServerClient from '@/lib/apiServerClient';
import pb from '@/lib/pocketbaseClient';

export default function CampaignGovernancePanel({ ads = [] }) {
  const [state, setState] = useState({ campaigns: {}, saved_views: [] });
  const [summary, setSummary] = useState({ campaigns: 0, overdue: 0, open_checklist: 0, saved_views: 0 });
  const [campaignId, setCampaignId] = useState('');
  const [draft, setDraft] = useState({ note: '', assignee: '', due_at: '', tags: '', checklist: '', view: '' });
  const [error, setError] = useState('');
  const isCreator = pb.authStore.model?.role === 'creator';
  const current = state.campaigns?.[campaignId] || {};
  const selected = useMemo(() => ads.find((item) => String(item.id) === campaignId), [ads, campaignId]);
  const load = async () => { const response = await apiServerClient.fetch('/house-ads/governance', { headers: { Authorization: `Bearer ${pb.authStore.token}` } }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setState(data.state || {}); setSummary(data.summary || {}); };
  useEffect(() => { if (!campaignId && ads[0]) setCampaignId(String(ads[0].id)); load().catch((cause) => setError(cause.message)); }, [ads]);
  useEffect(() => { setDraft((value) => ({ ...value, note: '', checklist: '', assignee: current.assignee || '', due_at: String(current.due_at || '').slice(0, 16), tags: (current.tags || []).join(', ') })); }, [campaignId, current.updated_at]);
  const act = async (body) => { setError(''); const response = await apiServerClient.fetch('/house-ads/governance', { method: 'POST', headers: { Authorization: `Bearer ${pb.authStore.token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ ...body, campaign_id: campaignId }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setState(data.state); setSummary(data.summary); };
  if (!ads.length) return null;
  return <section className="mt-5 rounded-xl border p-4"><div className="mb-3 flex flex-wrap items-start justify-between gap-2"><div><h4 className="font-semibold">Gobernanza de campañas</h4><p className="text-xs text-muted-foreground">Coordina revisiones sin alterar la entrega ni los permisos publicitarios.</p></div><select className="h-9 max-w-xs rounded-md border bg-background px-2 text-sm" value={campaignId} onChange={(event) => setCampaignId(event.target.value)}>{ads.map((ad) => <option key={ad.id} value={ad.id}>{ad.title || ad.id}</option>)}</select></div>
    {error && <p className="mb-3 rounded-md border border-red-300 bg-red-50 p-2 text-xs text-red-700">{error}</p>}
    <div className="mb-4 grid gap-2 sm:grid-cols-4">{[['Campañas coordinadas', summary.campaigns], ['Vencidas', summary.overdue], ['Tareas abiertas', summary.open_checklist], ['Vistas guardadas', summary.saved_views]].map(([label, value]) => <div key={label} className="rounded-lg border p-3"><b className="text-xl">{value || 0}</b><small className="block text-muted-foreground">{label}</small></div>)}</div>
    <div className="grid gap-3 lg:grid-cols-2"><div className="space-y-2 rounded-lg border p-3"><p className="flex items-center gap-2 text-sm font-semibold"><MessageSquare className="h-4 w-4"/>Notas de revisión</p><div className="flex gap-2"><Input value={draft.note} onChange={(e) => setDraft({ ...draft, note: e.target.value })} placeholder="Añadir nota interna"/><Button size="sm" onClick={() => act({ action: 'note', text: draft.note }).then(() => setDraft({ ...draft, note: '' })).catch((e) => setError(e.message))}>Añadir</Button></div>{(current.notes || []).slice(0, 5).map((item) => <p key={item.id} className="rounded bg-muted p-2 text-xs">{item.text}</p>)}</div>
      <div className="space-y-2 rounded-lg border p-3"><p className="flex items-center gap-2 text-sm font-semibold"><UserRound className="h-4 w-4"/>Responsable y vencimiento</p><Input value={draft.assignee} onChange={(e) => setDraft({ ...draft, assignee: e.target.value })} placeholder="ID o nombre del responsable"/><Input type="datetime-local" value={draft.due_at} onChange={(e) => setDraft({ ...draft, due_at: e.target.value })}/><Button size="sm" variant="outline" onClick={async () => { try { await act({ action: 'assign', assignee: draft.assignee }); await act({ action: 'due_date', due_at: draft.due_at }); } catch (e) { setError(e.message); } }}><CalendarClock className="mr-1 h-4 w-4"/>Guardar</Button></div>
      <div className="space-y-2 rounded-lg border p-3"><p className="flex items-center gap-2 text-sm font-semibold"><Tags className="h-4 w-4"/>Etiquetas y seguimiento</p><Input value={draft.tags} onChange={(e) => setDraft({ ...draft, tags: e.target.value })} placeholder="seguridad, urgente"/><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => act({ action: 'tags', tags: draft.tags.split(',') }).catch((e) => setError(e.message))}>Guardar etiquetas</Button><Button size="sm" variant="outline" onClick={() => act({ action: 'watch', enabled: !(current.watchers || []).includes(pb.authStore.model?.id) }).catch((e) => setError(e.message))}><Bell className="mr-1 h-4 w-4"/>{(current.watchers || []).includes(pb.authStore.model?.id) ? 'Dejar de seguir' : 'Seguir'}</Button></div></div>
      <div className="space-y-2 rounded-lg border p-3"><p className="flex items-center gap-2 text-sm font-semibold"><CheckSquare className="h-4 w-4"/>Lista de aprobación</p><div className="flex gap-2"><Input value={draft.checklist} onChange={(e) => setDraft({ ...draft, checklist: e.target.value })} placeholder="Comprobar destino"/><Button size="sm" onClick={() => act({ action: 'checklist', item: draft.checklist, completed: false }).then(() => setDraft({ ...draft, checklist: '' })).catch((e) => setError(e.message))}>Añadir</Button></div>{(current.checklist || []).map((item) => <button type="button" key={item.id} className="block w-full rounded border p-2 text-left text-xs" onClick={() => act({ action: 'checklist', item: item.text, completed: !item.completed }).catch((e) => setError(e.message))}>{item.completed ? '✓' : '○'} {item.text}</button>)}</div></div>
    {isCreator && <div className="mt-3 flex flex-wrap gap-2"><Input className="max-w-xs" value={draft.view} onChange={(e) => setDraft({ ...draft, view: e.target.value })} placeholder="Nombre de vista guardada"/><Button size="sm" variant="outline" onClick={() => act({ action: 'saved_view', name: draft.view, filters: { campaign_id: campaignId } }).catch((e) => setError(e.message))}>Guardar vista</Button><Button size="sm" variant="outline" onClick={() => act({ action: 'snapshot', summary: `${selected?.title || campaignId}: ${current.checklist?.filter((item) => item.completed).length || 0}/${current.checklist?.length || 0} revisiones` }).catch((e) => setError(e.message))}>Crear instantánea</Button></div>}
  </section>;
}
