import React, { useState } from 'react';
import { BrainCog } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import apiServerClient from '@/lib/apiServerClient';
import pb from '@/lib/pocketbaseClient';

const MoonbotAIAdvancedTools = ({ groups = [] }) => {
  const [groupId, setGroupId] = useState(groups[0]?.id || ''); const [questions, setQuestions] = useState(''); const [unanswered, setUnanswered] = useState([]); const [model, setModel] = useState(''); const [correct, setCorrect] = useState(''); const [total, setTotal] = useState(''); const [latency, setLatency] = useState(''); const [cost, setCost] = useState(''); const [memoryIndex, setMemoryIndex] = useState(''); const [message, setMessage] = useState('');
  const run = async (action, extra = {}) => { try { const response = await apiServerClient.fetch('/moonbot-admin/ai-center', { method: 'POST', headers: { Authorization: `Bearer ${pb.authStore.token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ action, group_id: groupId, ...extra }) }); const data = await response.json(); if (!response.ok || !data.ok) throw new Error(data.error || `HTTP ${response.status}`); setMessage('OperaciÃ³n completada.'); return data.result; } catch (cause) { setMessage(cause.message); return null; } };
  const analyze = async () => { const messages = questions.split('\n').filter(Boolean).map((text, index) => ({ id: String(index + 1), text })); const result = await run('unanswered', { messages }); setUnanswered(result?.questions || []); };
  return <Card className="mt-8 border-indigo-500/20"><CardHeader><CardTitle className="flex items-center gap-2"><BrainCog className="h-5 w-5 text-indigo-600" />Herramientas avanzadas de IA</CardTitle><CardDescription>Lagunas de conocimiento, calidad-coste y eliminaciÃ³n selectiva de memoria.</CardDescription></CardHeader><CardContent className="space-y-5"><section className="rounded-xl border p-4"><h3 className="mb-2 font-semibold">Preguntas sin respuesta</h3><Textarea value={questions} onChange={(event) => setQuestions(event.target.value)} placeholder="Una pregunta o mensaje por lÃ­nea" /><Button className="mt-2" variant="outline" onClick={analyze}>Detectar lagunas</Button>{unanswered.map((item) => <p key={item.id} className="mt-2 rounded-lg bg-amber-500/10 p-2 text-sm">{item.text}</p>)}</section><section className="rounded-xl border p-4"><h3 className="mb-2 font-semibold">EvaluaciÃ³n de modelo</h3><div className="grid gap-2 sm:grid-cols-5"><Input value={model} onChange={(event) => setModel(event.target.value)} placeholder="Modelo" /><Input value={correct} onChange={(event) => setCorrect(event.target.value)} type="number" placeholder="Correctas" /><Input value={total} onChange={(event) => setTotal(event.target.value)} type="number" placeholder="Total" /><Input value={latency} onChange={(event) => setLatency(event.target.value)} type="number" placeholder="Latencia ms" /><Input value={cost} onChange={(event) => setCost(event.target.value)} type="number" step="0.0001" placeholder="Coste" /></div><Button className="mt-2" onClick={() => run('evaluate', { model, correct: +correct, total: +total, latency_ms: +latency, cost: +cost })}>Guardar mediciÃ³n</Button></section><section className="rounded-xl border p-4"><h3 className="mb-2 font-semibold">Borrado selectivo de memoria</h3><div className="grid gap-2 sm:grid-cols-3"><select className="h-10 rounded-md border bg-background px-3" value={groupId} onChange={(event) => setGroupId(event.target.value)}>{groups.map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</select><Input value={memoryIndex} onChange={(event) => setMemoryIndex(event.target.value)} type="number" min="0" placeholder="Ãndice de memoria" /><Button variant="destructive" disabled={!groupId || memoryIndex === ''} onClick={() => run('memory_delete', { index: +memoryIndex })}>Eliminar entrada</Button></div></section>{message && <p className="rounded-lg bg-muted/40 p-3 text-sm">{message}</p>}</CardContent></Card>;
};
export default MoonbotAIAdvancedTools;
