import React, { useEffect, useMemo, useState } from 'react';
import { Bell, Contrast, History, LayoutDashboard, Search, Star, Text, WandSparkles, WifiOff } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'; import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Badge } from '@/components/ui/badge';
import apiServerClient from '@/lib/apiServerClient'; import pb from '@/lib/pocketbaseClient';

const pendingKey = 'moonbot-experience-pending';
const MoonbotExperienceCenter = ({ groups = [] }) => {
  const [data, setData] = useState(null); const [query, setQuery] = useState(''); const [error, setError] = useState(''); const [offline, setOffline] = useState(!navigator.onLine); const [tour, setTour] = useState(-1);
  const [groupId, setGroupId] = useState(String(groups[0]?.id || groups[0]?.chat_id || ''));
  const fetchApi = async (body) => { const response = await apiServerClient.fetch('/moonbot-admin/experience', { method: body ? 'POST' : 'GET', headers: { Authorization: `Bearer ${pb.authStore.token}`, ...(body ? { 'Content-Type': 'application/json' } : {}) }, body: body ? JSON.stringify(body) : undefined }); const payload = await response.json(); if (!response.ok || !payload.ok) throw new Error(payload.error || `HTTP ${response.status}`); return payload; };
  const load = async () => { try { setData(await fetchApi()); setError(''); } catch (reason) { setError(reason.message); } };
  const save = async (changes) => { const next = { ...(data?.preferences || {}), ...changes }; setData((old) => ({ ...old, preferences: next })); localStorage.setItem(pendingKey, JSON.stringify(next)); if (!navigator.onLine) return; try { await fetchApi({ action: 'preferences', preferences: next }); localStorage.removeItem(pendingKey); } catch (reason) { setError(`${reason.message}. Se sincronizará al recuperar conexión.`); } };
  useEffect(() => { const online = async () => { setOffline(false); const pending = JSON.parse(localStorage.getItem(pendingKey) || 'null'); if (pending) { try { await fetchApi({ action: 'preferences', preferences: pending }); localStorage.removeItem(pendingKey); } catch {} } load(); }; const off = () => setOffline(true); addEventListener('online', online); addEventListener('offline', off); load(); return () => { removeEventListener('online', online); removeEventListener('offline', off); }; }, []);
  useEffect(() => { const p = data?.preferences; if (!p) return; document.documentElement.style.fontSize = `${p.font_scale || 100}%`; document.documentElement.classList.toggle('moon-admin-contrast', !!p.high_contrast); document.documentElement.classList.toggle('moon-admin-compact', !!p.compact); document.documentElement.classList.toggle('moon-admin-reduced-motion', !!p.reduced_motion); }, [data?.preferences]);
  const actions = useMemo(() => (data?.actions || []).filter((item) => `${item.name} ${item.area}`.toLowerCase().includes(query.toLowerCase())), [data, query]); const preferences = data?.preferences || {};
  const open = (action) => { document.getElementById(`moon-${action.id}`)?.scrollIntoView({ behavior: preferences.reduced_motion ? 'auto' : 'smooth' }); const history = [...(preferences.history || []), { id: action.id, name: action.name, at: new Date().toISOString() }].slice(-30); save({ history }); };
  const favorite = (id) => save({ favorites: preferences.favorites?.includes(id) ? preferences.favorites.filter((x) => x !== id) : [...(preferences.favorites || []), id] });
  const steps = ['Busca cualquier acción del panel', 'Marca tus herramientas favoritas', 'Configura accesibilidad y densidad', 'Elige los widgets y el tema de cada grupo'];
  return <Card className="mt-8 border-fuchsia-500/20"><CardHeader><CardTitle className="flex items-center gap-2"><LayoutDashboard className="h-5 w-5 text-fuchsia-600"/>Experiencia del panel</CardTitle><CardDescription>Personaliza la administración y conserva tus preferencias en la web y la MiniApp.</CardDescription></CardHeader><CardContent className="space-y-5">
    {offline && <p className="flex items-center gap-2 rounded-lg bg-amber-500/10 p-3 text-sm"><WifiOff className="h-4 w-4"/>Sin conexión: los cambios quedan guardados para sincronizarlos después.</p>}{error && <p className="text-sm text-red-600">{error}</p>}
    <div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" placeholder="Buscar acciones y ajustes…" value={query} onChange={(e) => setQuery(e.target.value)}/></div>
    <div className="grid gap-2 md:grid-cols-2">{actions.map((action) => <div key={action.id} className="flex items-center justify-between rounded-lg border p-3"><button className="text-left" onClick={() => open(action)}><b className="block text-sm">{action.name}</b><span className="text-xs text-muted-foreground">{action.area}</span></button><button aria-label="Favorito" onClick={() => favorite(action.id)}><Star className={`h-5 w-5 ${preferences.favorites?.includes(action.id) ? 'fill-amber-400 text-amber-500' : 'text-muted-foreground'}`}/></button></div>)}</div>
    <div className="grid gap-4 lg:grid-cols-3"><section className="space-y-3 rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><Bell className="h-4 w-4"/>Notificaciones</h3>{data?.notifications?.map((item) => <p key={item.id} className="flex justify-between text-sm"><span>{item.title}</span><Badge>{item.count}</Badge></p>)}{!data?.notifications?.length && <p className="text-sm text-muted-foreground">Todo al día.</p>}</section>
      <section className="space-y-3 rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><Contrast className="h-4 w-4"/>Vista y accesibilidad</h3><label className="flex justify-between text-sm">Modo compacto<input type="checkbox" checked={!!preferences.compact} onChange={(e) => save({ compact: e.target.checked })}/></label><label className="flex justify-between text-sm">Alto contraste<input type="checkbox" checked={!!preferences.high_contrast} onChange={(e) => save({ high_contrast: e.target.checked })}/></label><label className="flex justify-between text-sm">Reducir movimiento<input type="checkbox" checked={!!preferences.reduced_motion} onChange={(e) => save({ reduced_motion: e.target.checked })}/></label><label className="text-sm"><Text className="mr-2 inline h-4 w-4"/>Texto {preferences.font_scale || 100}%<input className="w-full" type="range" min="80" max="140" value={preferences.font_scale || 100} onChange={(e) => save({ font_scale: Number(e.target.value) })}/></label></section>
      <section className="space-y-3 rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><WandSparkles className="h-4 w-4"/>Tema por grupo</h3><select className="h-10 w-full rounded-md border bg-background px-3" value={groupId} onChange={(e) => setGroupId(e.target.value)}>{groups.map((g) => <option key={g.id || g.chat_id} value={g.id || g.chat_id}>{g.name || g.title || g.id}</option>)}</select><select className="h-10 w-full rounded-md border bg-background px-3" value={data?.themes?.[groupId] || 'default'} onChange={async (e) => { await fetchApi({ action: 'theme', group_id: groupId, theme: e.target.value }); load(); }}><option value="default">Predeterminado</option><option value="moon">Moon</option><option value="ocean">Océano</option><option value="forest">Bosque</option><option value="sunset">Atardecer</option><option value="contrast">Alto contraste</option></select><Button variant="outline" onClick={() => setTour(0)}>Iniciar recorrido</Button></section></div>
    <section className="rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><History className="h-4 w-4"/>Historial y widgets</h3><div className="mt-2 flex flex-wrap gap-2">{['summary', 'groups', 'security', 'ai', 'automations', 'integrations', 'operations'].map((item) => <button key={item} onClick={() => save({ widgets: preferences.widgets?.includes(item) ? preferences.widgets.filter((x) => x !== item) : [...(preferences.widgets || []), item] })}><Badge variant={preferences.widgets?.includes(item) ? 'default' : 'outline'}>{item}</Badge></button>)}</div><p className="mt-2 text-xs text-muted-foreground">{preferences.history?.length || 0} acciones recientes guardadas.</p></section>
    {tour >= 0 && <div className="fixed inset-0 z-[100] grid place-items-center bg-black/60 p-4"><div className="w-full max-w-md rounded-2xl bg-background p-6 shadow-2xl"><Badge>Paso {tour + 1}/{steps.length}</Badge><h3 className="mt-3 text-xl font-bold">{steps[tour]}</h3><div className="mt-5 flex gap-2"><Button variant="outline" onClick={() => setTour(-1)}>Cerrar</Button><Button onClick={() => { if (tour + 1 < steps.length) setTour(tour + 1); else { save({ tour_completed: true }); setTour(-1); } }}>{tour + 1 < steps.length ? 'Siguiente' : 'Finalizar'}</Button></div></div></div>}
  </CardContent></Card>;
}; export default MoonbotExperienceCenter;
