import React, { useEffect, useMemo, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
const defs=[
[(x)=>x.startsWith('optimize_')&&x.endsWith('_energy'),['Carga','Wh','Elementos'],['worker-1','20','10'],(v)=>({args:[[{workload_id:v[0],energy_wh:Number(v[1]),items:Number(v[2])}]],kwargs:{target_reduction:10}})],
[(x)=>x.startsWith('limit_')&&x.endsWith('_abuse'),['Sujeto','Evento','Límite'],['user-1','event-1','10'],(v)=>({args:[[{subject_id:v[0],event_id:v[1],occurred_at:new Date().toISOString()}],{window_seconds:60,limit:Number(v[2]),burst:2}],kwargs:{}})],
[(x)=>x.endsWith('_guided_migration'),['Registro','Origen','Destino'],['record-1','v1','v2'],(v)=>({args:[[{id:v[0]}],{source_version:v[1],target_version:v[2],required_fields:[]}],kwargs:{}})],
[(x)=>x.endsWith('_federated_compatibility'),['Origen','Sujeto','Esquema'],['node-1','item-1','v1'],(v)=>({args:[{origin:v[0],subject_id:v[1],schema_version:v[2],issued_at:new Date().toISOString(),expires_at:new Date(Date.now()+86400000).toISOString()},{allowed_origins:[v[0]],schema_versions:[v[2]]}],kwargs:{}})],
[(x)=>x.endsWith('_operational_continuity'),['Servicio','RTO','RPO'],['service-1','60','15'],(v)=>({args:[[{service_id:v[0],dependencies:[],backup_available:true,fallback_available:true}]],kwargs:{rto_minutes:Number(v[1]),rpo_minutes:Number(v[2])}})],
[(x)=>x.endsWith('_contextually'),['Contexto','Estado','Severidad'],['context-1','pending','warning'],(v)=>({args:[{context_id:v[0],state:v[1],severity:v[2],missing_fields:[]}],kwargs:{}})],
[(x)=>x.startsWith('run_')&&x.endsWith('_isolated_sandbox'),['Ejecución','Pasos','Elementos'],['run-1','10','100'],(v)=>({args:[{run_id:v[0],operation:'simulate',inputs:{},budget:{max_steps:Number(v[1]),max_items:Number(v[2]),timeout_ms:1000}}],kwargs:{}})],
[(x)=>x.startsWith('review_')&&x.endsWith('_proposal_governance'),['Propuesta','Proponente','Votante'],['proposal-1','user-1','user-2'],(v)=>({args:[{proposal_id:v[0],proposer_id:v[1],opens_at:new Date().toISOString(),closes_at:new Date(Date.now()+86400000).toISOString(),quorum:1,eligible_voter_ids:[v[1],v[2]]},[{voter_id:v[2],choice:'approve'}]],kwargs:{}})],
[(x)=>x.startsWith('measure_')&&x.endsWith('_impact'),['Métrica','Base','Actual'],['success_rate','50','75'],(v)=>({args:[[{metric:v[0],period:'baseline',value:Number(v[1])},{metric:v[0],period:'current',value:Number(v[2])}]],kwargs:{}})],
[(x)=>x.startsWith('plan_')&&x.endsWith('_scheduled_archive'),['Registro','Retención','Destino'],['record-1','3650','archive-vault-1'],(v)=>{const now=Date.now();return{args:[[{id:v[0],updated_at:new Date(now-86400000*30).toISOString(),state:'active',legal_hold:false,size_bytes:0,version:1}],{evaluated_at:new Date(now).toISOString(),run_at:new Date(now+3600000).toISOString(),cutoff_before:new Date(now-86400000).toISOString(),retention_days:Number(v[1]),batch_size:100,destination_id:v[2],encryption_key_version:1}],kwargs:{}}}],
[(x)=>x.startsWith('review_')&&x.endsWith('_quality'),['Registro','Umbral','Identificador'],['record-1','90','record-1'],(v)=>({args:[[{id:v[2]}]],kwargs:{threshold:Number(v[1])}})],
];
export default function MoonbotFeatureSpecificForm({feature,onPrepare}){const d=useMemo(()=>defs.find(([test])=>test(feature?.api||'')),[feature]);const[v,setV]=useState([]);useEffect(()=>setV(d?.[2]||[]),[feature?.id,d]);if(!d)return null;return <section className="space-y-3 rounded-xl border border-primary/20 bg-primary/5 p-4"><b>Formulario específico</b><div className="grid gap-2 sm:grid-cols-3">{d[1].map((label,i)=><label key={label} className="text-xs">{label}<Input className="mt-1" value={v[i]||''} onChange={(e)=>setV((old)=>old.map((x,p)=>p===i?e.target.value:x))}/></label>)}</div><Button size="sm" variant="secondary" onClick={()=>onPrepare(JSON.stringify(d[3](v),null,2))}>Preparar solicitud</Button><p className="text-xs text-muted-foreground">No ejecuta cambios: prepara el contrato para revisarlo.</p></section>}
