import React, { useEffect, useState } from 'react';
import { Bot, CalendarClock, FlaskConical, RefreshCw, Webhook, Workflow } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import apiServerClient from '@/lib/apiServerClient';
import pb from '@/lib/pocketbaseClient';

const MoonbotAutomationsCenter = ({ groups = [] }) => {
  const [data, setData] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [groupId, setGroupId] = useState(String(groups[0]?.id || groups[0]?.chat_id || ''));
  const [rule, setRule] = useState({ keyword: '', response: '', role: '' }); const [simulation, setSimulation] = useState('');
  const [simulationResult, setSimulationResult] = useState(null); const [form, setForm] = useState({ title: '', fields: 'Nombre,Descripción' });
  const [hook, setHook] = useState({ url: '', events: 'member_join,message_reported' }); const [schedule, setSchedule] = useState({ at: '', text: '' });
  const call = async (body) => { setBusy(true); setError(''); try { const response = await apiServerClient.fetch('/moonbot-admin/automations', { method: body ? 'POST' : 'GET', headers: { Authorization: `Bearer ${pb.authStore.token}`, ...(body ? { 'Content-Type': 'application/json' } : {}) }, body: body ? JSON.stringify(body) : undefined }); const payload = await response.json(); if (!response.ok || !payload.ok) throw new Error(payload.error || `HTTP ${response.status}`); if (!body) setData(payload); return payload; } catch (reason) { setError(reason.message); return null; } finally { setBusy(false); } };
  const mutate = async (body) => { const result = await call({ ...body, group_id: groupId }); if (result) await call(); return result; };
  useEffect(() => { call(); }, []);
  const parseFields = () => form.fields.split(',').map((label, index) => ({ name: `field_${index + 1}`, label: label.trim(), type: index ? 'textarea' : 'text', required: index === 0 })).filter((item) => item.label);
  return <Card className="mt-8 border-violet-500/20"><CardHeader><CardTitle className="flex items-center gap-2"><Workflow className="h-5 w-5 text-violet-600" />Automatizaciones Moonbot</CardTitle><CardDescription>Construye flujos sin código, pruébalos y controla su ejecución desde la web.</CardDescription></CardHeader><CardContent className="space-y-6">
    <div className="flex flex-wrap gap-3"><select className="h-10 min-w-60 rounded-md border bg-background px-3" value={groupId} onChange={(event) => setGroupId(event.target.value)}>{groups.map((group) => <option key={group.id || group.chat_id} value={group.id || group.chat_id}>{group.title || group.name || group.id}</option>)}</select><Button variant="outline" onClick={() => call()} disabled={busy}><RefreshCw className={`mr-2 h-4 w-4 ${busy ? 'animate-spin' : ''}`} />Actualizar</Button></div>
    {error && <p className="rounded-lg bg-red-500/10 p-3 text-sm text-red-600">{error}</p>}
    <div className="grid gap-4 xl:grid-cols-2">
      <section className="space-y-3 rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><Bot className="h-4 w-4" />Regla visual y respuesta automática</h3><Input placeholder="Palabra o frase que activa la regla" value={rule.keyword} onChange={(e) => setRule({ ...rule, keyword: e.target.value })}/><Input placeholder="Respuesta de Moonbot" value={rule.response} onChange={(e) => setRule({ ...rule, response: e.target.value })}/><Input placeholder="Rol opcional (member, admin...)" value={rule.role} onChange={(e) => setRule({ ...rule, role: e.target.value })}/><Button onClick={() => mutate({ action: 'rule_save', keyword: rule.keyword, response: rule.response, conditions: rule.role ? { role: rule.role } : {} })}>Guardar regla</Button></section>
      <section className="space-y-3 rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><FlaskConical className="h-4 w-4" />Simulador sin ejecución</h3><Input placeholder="Escribe un mensaje de prueba" value={simulation} onChange={(e) => setSimulation(e.target.value)}/><Button variant="outline" onClick={async () => { const value = await call({ action: 'simulate', group_id: groupId, text: simulation, context: {} }); setSimulationResult(value?.result?.matched || null); }}>Simular</Button><p className="text-sm text-muted-foreground">{simulationResult ? `Coincide con “${simulationResult.keyword}” → ${simulationResult.response}` : 'La simulación no publica mensajes ni ejecuta acciones.'}</p></section>
      <section className="space-y-3 rounded-xl border p-4"><h3 className="font-semibold">Formulario adaptable</h3><Input placeholder="Título" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })}/><Input placeholder="Campos separados por comas" value={form.fields} onChange={(e) => setForm({ ...form, fields: e.target.value })}/><Button onClick={() => mutate({ action: 'form_save', title: form.title, fields: parseFields() })}>Crear formulario</Button></section>
      <section className="space-y-3 rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><Webhook className="h-4 w-4" />Webhook seguro</h3><Input placeholder="https://tu-servidor.example/eventos" value={hook.url} onChange={(e) => setHook({ ...hook, url: e.target.value })}/><Input placeholder="Eventos separados por comas" value={hook.events} onChange={(e) => setHook({ ...hook, events: e.target.value })}/><Button onClick={() => mutate({ action: 'webhook_save', url: hook.url, events: hook.events.split(',').map((x) => x.trim()).filter(Boolean) })}>Guardar webhook</Button></section>
      <section className="space-y-3 rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><CalendarClock className="h-4 w-4" />Calendario de acciones</h3><Input type="datetime-local" value={schedule.at} onChange={(e) => setSchedule({ ...schedule, at: e.target.value })}/><Input placeholder="Mensaje programado" value={schedule.text} onChange={(e) => setSchedule({ ...schedule, text: e.target.value })}/><Button onClick={() => mutate({ action: 'calendar', calendar_action: 'message', execute_at: schedule.at, payload: { text: schedule.text } })}>Programar acción</Button></section>
      <section className="space-y-3 rounded-xl border p-4"><h3 className="font-semibold">Biblioteca de automatizaciones</h3>{data?.templates?.map((template) => <div key={template.id} className="flex items-center justify-between gap-3 rounded-lg bg-muted/30 p-3"><div><p className="text-sm font-medium">{template.name}</p><p className="text-xs text-muted-foreground">{template.description}</p></div><Button size="sm" variant="outline" onClick={() => mutate({ action: 'automation_install', template_id: template.id })}>Instalar</Button></div>)}</section>
    </div>
    <section className="rounded-xl border p-4"><h3 className="mb-3 font-semibold">Colas, reintentos y cancelación</h3><div className="space-y-2">{data?.queue?.map((task) => <div key={task.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-muted/30 p-3 text-sm"><span>#{task.id} · {task.type} · <Badge variant="secondary">{task.status}</Badge></span><span className="space-x-2"><Button size="sm" variant="outline" onClick={() => mutate({ action: 'queue_prioritize', task_id: task.id })}>Priorizar</Button><Button size="sm" variant="destructive" onClick={() => mutate({ action: 'queue_cancel', task_id: task.id })}>Cancelar</Button></span></div>)}{data?.webhook_queue?.map((job) => <div key={job.id} className="flex items-center justify-between gap-2 rounded-lg bg-muted/30 p-3 text-sm"><span>Webhook {job.event} · {job.status} · {job.attempts} intentos</span>{['retry', 'dead_letter'].includes(job.status) && <Button size="sm" variant="outline" onClick={() => mutate({ action: 'webhook_retry', job_id: job.id })}>Reintentar</Button>}</div>)}{!data?.queue?.length && !data?.webhook_queue?.length && <p className="text-sm text-muted-foreground">No hay trabajos pendientes.</p>}</div></section>
    <div className="flex flex-wrap gap-2 text-xs"><Badge variant="outline">{data?.rules?.length || 0} reglas</Badge><Badge variant="outline">{data?.forms?.length || 0} formularios</Badge><Badge variant="outline">{data?.webhooks?.length || 0} webhooks</Badge><Badge variant="outline">{data?.calendar?.length || 0} acciones programadas</Badge></div>
  </CardContent></Card>;
};

export default MoonbotAutomationsCenter;
