import React, { useEffect, useState } from 'react';
import { Boxes, Code2, KeyRound, PlugZap, RefreshCw, ShieldCheck } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Badge } from '@/components/ui/badge';
import apiServerClient from '@/lib/apiServerClient'; import pb from '@/lib/pocketbaseClient';

const scopes = ['groups:read', 'groups:write', 'users:read', 'moderation:write', 'analytics:read', 'content:write', 'webhooks:write'];
const MoonbotIntegrationsCenter = ({ groups = [] }) => {
  const [data, setData] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [secret, setSecret] = useState('');
  const [groupId, setGroupId] = useState(String(groups[0]?.id || groups[0]?.chat_id || '')); const [token, setToken] = useState({ name: '', scopes: ['groups:read'] });
  const [module, setModule] = useState({ name: '', version: '1.0.0', checksum: '', permissions: '' }); const [botId, setBotId] = useState('');
  const [quota, setQuota] = useState({ method: 'sendMessage', used: 0, limit: 1000 }); const [external, setExternal] = useState({ provider: '', id: '', title: '' });
  const [bundle, setBundle] = useState('');
  const request = async (body) => { setBusy(true); setError(''); try { const response = await apiServerClient.fetch('/moonbot-admin/integrations', { method: body ? 'POST' : 'GET', headers: { Authorization: `Bearer ${pb.authStore.token}`, ...(body ? { 'Content-Type': 'application/json' } : {}) }, body: body ? JSON.stringify(body) : undefined }); const payload = await response.json(); if (!response.ok || !payload.ok) throw new Error(payload.error || `HTTP ${response.status}`); if (!body) setData(payload); return payload; } catch (reason) { setError(reason.message); return null; } finally { setBusy(false); } };
  const mutate = async (body) => { const result = await request(body); if (result?.result?.token) setSecret(result.result.token); if (body.action === 'config_export' && result?.result) setBundle(JSON.stringify(result.result, null, 2)); if (result) await request(); };
  useEffect(() => { request(); }, []);
  const toggleScope = (scope) => setToken({ ...token, scopes: token.scopes.includes(scope) ? token.scopes.filter((x) => x !== scope) : [...token.scopes, scope] });
  return <Card className="mt-8 border-indigo-500/20"><CardHeader><CardTitle className="flex items-center gap-2"><PlugZap className="h-5 w-5 text-indigo-600" />Integraciones y API Moonbot</CardTitle><CardDescription>Conecta servicios externos con permisos mínimos, credenciales rotables y configuración firmada.</CardDescription></CardHeader><CardContent className="space-y-6">
    <div className="flex flex-wrap gap-3"><select className="h-10 min-w-60 rounded-md border bg-background px-3" value={groupId} onChange={(e) => setGroupId(e.target.value)}>{groups.map((group) => <option key={group.id || group.chat_id} value={group.id || group.chat_id}>{group.title || group.name || group.id}</option>)}</select><Button variant="outline" disabled={busy} onClick={() => request()}><RefreshCw className={`mr-2 h-4 w-4 ${busy ? 'animate-spin' : ''}`}/>Actualizar</Button></div>
    {error && <p className="rounded-lg bg-red-500/10 p-3 text-sm text-red-600">{error}</p>}{secret && <div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4"><p className="font-semibold">Token nuevo — cópialo ahora; no volverá a mostrarse</p><code className="mt-2 block break-all text-sm">{secret}</code><Button className="mt-3" size="sm" variant="outline" onClick={() => navigator.clipboard.writeText(secret)}>Copiar</Button></div>}
    <div className="grid gap-4 xl:grid-cols-2">
      <section className="space-y-3 rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><KeyRound className="h-4 w-4"/>Token API con ámbitos</h3><Input placeholder="Nombre de la integración" value={token.name} onChange={(e) => setToken({ ...token, name: e.target.value })}/><div className="flex flex-wrap gap-2">{scopes.map((scope) => <button key={scope} onClick={() => toggleScope(scope)} className={`rounded-full border px-2 py-1 text-xs ${token.scopes.includes(scope) ? 'bg-indigo-600 text-white' : ''}`}>{scope}</button>)}</div><Button onClick={() => mutate({ action: 'token_create', ...token })}>Crear token</Button></section>
      <section className="space-y-3 rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><Boxes className="h-4 w-4"/>Registrar módulo</h3><div className="grid grid-cols-2 gap-2"><Input placeholder="Nombre" value={module.name} onChange={(e) => setModule({ ...module, name: e.target.value })}/><Input placeholder="Versión" value={module.version} onChange={(e) => setModule({ ...module, version: e.target.value })}/></div><Input placeholder="Checksum SHA-256" value={module.checksum} onChange={(e) => setModule({ ...module, checksum: e.target.value })}/><Input placeholder="Permisos separados por comas" value={module.permissions} onChange={(e) => setModule({ ...module, permissions: e.target.value })}/><Button onClick={() => mutate({ action: 'module_register', ...module, permissions: module.permissions.split(',').filter(Boolean) })}>Registrar sin verificar</Button></section>
      <section className="space-y-3 rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><ShieldCheck className="h-4 w-4"/>Sandbox y cuota</h3><Input placeholder="ID del bot" value={botId} onChange={(e) => setBotId(e.target.value)}/><div className="flex gap-2"><Button variant="outline" onClick={() => mutate({ action: 'sandbox', bot_id: botId, enabled: true })}>Activar sandbox</Button><Button variant="outline" onClick={() => mutate({ action: 'sandbox', bot_id: botId, enabled: false })}>Desactivar</Button></div><div className="grid grid-cols-3 gap-2"><Input value={quota.method} onChange={(e) => setQuota({ ...quota, method: e.target.value })}/><Input type="number" value={quota.used} onChange={(e) => setQuota({ ...quota, used: e.target.value })}/><Input type="number" value={quota.limit} onChange={(e) => setQuota({ ...quota, limit: e.target.value })}/></div><Button onClick={() => mutate({ action: 'quota', bot_id: botId, ...quota })}>Guardar cuota</Button></section>
      <section className="space-y-3 rounded-xl border p-4"><h3 className="font-semibold">Incidente o calendario externo</h3><Input placeholder="Proveedor (GitHub, Jira, Google...)" value={external.provider} onChange={(e) => setExternal({ ...external, provider: e.target.value })}/><Input placeholder="ID externo o ID de calendario" value={external.id} onChange={(e) => setExternal({ ...external, id: e.target.value })}/><Input placeholder="Título del incidente" value={external.title} onChange={(e) => setExternal({ ...external, title: e.target.value })}/><div className="flex gap-2"><Button onClick={() => mutate({ action: 'incident_link', group_id: groupId, provider: external.provider, external_id: external.id, title: external.title })}>Enlazar incidente</Button><Button variant="outline" onClick={() => mutate({ action: 'calendar_link', group_id: groupId, provider: external.provider, calendar_id: external.id })}>Enlazar calendario</Button></div></section>
      <section className="space-y-3 rounded-xl border p-4 xl:col-span-2"><h3 className="font-semibold">Configuración firmada</h3><textarea className="min-h-32 w-full rounded-md border bg-background p-3 font-mono text-xs" placeholder="Exporta un paquete firmado o pega uno para importarlo" value={bundle} onChange={(e) => setBundle(e.target.value)}/><div className="flex gap-2"><Button onClick={() => mutate({ action: 'config_export', group_id: groupId })}>Exportar y firmar</Button><Button variant="outline" onClick={() => { try { mutate({ action: 'config_import', bundle: JSON.parse(bundle) }); } catch { setError('El paquete no contiene JSON válido'); } }}>Verificar e importar</Button></div></section>
    </div>
    <section className="rounded-xl border p-4"><h3 className="mb-3 flex items-center gap-2 font-semibold"><KeyRound className="h-4 w-4"/>Credenciales activas</h3><div className="space-y-2">{data?.tokens?.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-muted/30 p-3 text-sm"><span>{item.name} · <code>{item.prefix}…</code> · <Badge variant="outline">{item.status}</Badge></span><span className="space-x-2"><Button size="sm" variant="outline" onClick={() => mutate({ action: 'token_rotate', token_id: item.id })}>Rotar</Button><Button size="sm" variant="destructive" disabled={item.status !== 'active'} onClick={() => mutate({ action: 'token_revoke', token_id: item.id })}>Revocar</Button></span></div>)}</div></section>
    <section className="rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><Code2 className="h-4 w-4"/>SDK de extensiones</h3><p className="mt-2 text-sm text-muted-foreground">{data?.sdk?.name} v{data?.sdk?.version} · autenticación: {data?.sdk?.authentication}</p><div className="mt-2 flex flex-wrap gap-2">{data?.sdk?.events?.map((event) => <Badge key={event} variant="secondary">{event}</Badge>)}</div></section>
  </CardContent></Card>;
};
export default MoonbotIntegrationsCenter;
