import React from 'react';
const value = (n, suffix = '') => n == null ? '—' : `${Number(n).toLocaleString('es-ES', { maximumFractionDigits: 1 })}${suffix}`;
const since = (date) => date ? new Date(date).toLocaleString('es-ES') : 'sin conexión';
function Stat({ label, count, detail, alert = false }) {
  return <div className={`rounded-xl border p-4 ${alert ? 'border-amber-500/40 bg-amber-500/5' : 'bg-muted/20'}`}><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{value(count)}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div>;
}
function Usage({ label, used, note }) {
  const percentage = used == null ? null : Math.max(0, Math.min(100, used));
  return <div><div className="mb-2 flex justify-between text-sm"><span>{label}</span><b>{value(used, '%')}</b></div><div role="progressbar" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={percentage ?? undefined} aria-valuetext={percentage == null ? 'Sin datos' : undefined} className="h-2 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full ${percentage >= 85 ? 'bg-amber-500' : 'bg-cyan-500'}`} style={{ width: `${percentage ?? 0}%` }} /></div><p className="mt-1 text-xs text-muted-foreground">{note}</p></div>;
}
function Chart({ history = [], lines }) {
  const max = Math.max(1, ...history.flatMap((row) => lines.map((line) => Number(row[line.key]) || 0)));
  if (!history.length) return <p className="mt-3 rounded-lg border border-dashed p-5 text-sm text-muted-foreground">Esperando muestras de tráfico.</p>;
  return <><svg viewBox="0 0 600 120" className="mt-3 h-32 w-full" role="img" aria-label="Tráfico por minuto; valores en la tabla desplegable"><path d="M0 110H600 M0 60H600 M0 10H600" stroke="currentColor" opacity="0.12" fill="none" />{lines.map((line) => <polyline key={line.key} fill="none" stroke={line.color} strokeWidth="2.5" points={history.map((row, i) => `${history.length === 1 ? 300 : i * 600 / (history.length - 1)},${110 - ((Number(row[line.key]) || 0) / max) * 100}`).join(' ')} />)}{history.length === 1 && lines.map((line) => <circle key={line.key} cx="300" cy={110 - ((Number(history[0][line.key]) || 0) / max) * 100} r="3" fill={line.color} />)}</svg><div className="flex flex-wrap gap-4 text-xs">{lines.map((line) => <span key={line.key} className="flex items-center gap-1"><span className="h-2 w-2 rounded-full" style={{ backgroundColor: line.color }} />{line.label}</span>)}<span className="text-muted-foreground">Escala 0–{value(max)} / minuto · minuto actual parcial</span></div><details className="mt-3 text-xs"><summary className="cursor-pointer">Ver valores por minuto ({history.length})</summary><div className="mt-2 max-h-44 overflow-auto"><table className="w-full text-left"><thead><tr><th className="p-2">Hora</th>{lines.map((line) => <th className="p-2" key={line.key}>{line.label}</th>)}</tr></thead><tbody>{history.map((row) => <tr key={row.at}><td className="p-2">{new Date(row.at).toLocaleTimeString()}</td>{lines.map((line) => <td key={line.key} className="p-2 tabular-nums">{value(row[line.key])}</td>)}</tr>)}</tbody></table></div></details></>;
}
export default function MoonbotTrafficPanel({ data }) {
  const ops = data?.operations;
  const telegram = ops?.last60s;
  const api = data?.api;
  const http = api?.last60s;
  const r = data?.resources;
  const node = data?.nodes?.find((item) => item.id === data.active);
  return <div className="space-y-5">
    <div className="rounded-xl border border-cyan-500/20 bg-cyan-500/5 p-4"><p className="text-sm font-medium">Telegram → Moonbot → API de Telegram · Web → API de todosobreall.tech</p><p className="mt-1 text-xs text-muted-foreground">Contadores agregados, sin textos, chats ni credenciales. Totales desde el arranque de cada proceso; hasta 60 minutos de histórico.</p></div>
    {!!data?.telemetryErrors?.length && <div role="status" className="space-y-1 rounded-xl border border-amber-500/30 p-3 text-xs text-amber-700 dark:text-amber-300">{data.telemetryErrors.map((error) => <p key={error}>{error}</p>)}</div>}
    <section className="rounded-xl border p-4"><div className="mb-4 flex flex-wrap items-baseline justify-between gap-2"><h3 className="text-lg font-semibold">Mensajes y llamadas de Telegram</h3><span className="text-xs text-muted-foreground">Desde {since(ops?.since)}</span></div>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Mensajes recibidos · 60 s" count={telegram?.received} detail={`${value(ops?.total?.received)} desde el arranque`} /><Stat label="Mensajes enviados · 60 s" count={telegram?.sent} detail={`${value(ops?.total?.sent)} confirmados desde el arranque`} /><Stat label="Llamadas a Telegram · 60 s" count={telegram?.calls} detail={`${value(ops?.total?.calls)} intentos, incluidos reintentos`} /><Stat label="Errores Telegram · 60 s" count={telegram?.errors} detail={`${value(telegram?.limited)} respuestas 429 · ${value(telegram?.timeouts)} timeouts`} alert={telegram?.errors > 0} /></div>
      <div className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><p>Updates recibidos: <b>{value(telegram?.updates)}</b></p><p>Latencia media: <b>{value(telegram?.calls > 0 ? telegram.latency_ms / telegram.calls : null, ' ms')}</b></p><p>Mayor espera 429: <b>{value(telegram?.retry_after_max, ' s')}</b></p></div><p className="mt-2 text-xs text-muted-foreground">Updates incluye botones y ediciones. Recibidos cuenta mensajes nuevos entregados por getUpdates, sin duplicar la misma entrega por bot. No prueba procesamiento correcto. Latencia incluye long polling.</p>
      <Chart history={ops?.history} lines={[{ key: 'received', label: 'Recibidos', color: '#0891b2' }, { key: 'sent', label: 'Enviados', color: '#7c3aed' }, { key: 'calls', label: 'Llamadas a Telegram', color: '#d97706' }]} />
    </section>
    <section className="rounded-xl border p-4"><div className="mb-4 flex flex-wrap items-baseline justify-between gap-2"><h3 className="text-lg font-semibold">Peticiones a la API de la web</h3><span className="text-xs text-muted-foreground">Este proceso Express · desde {since(api?.since)}</span></div>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Peticiones observadas · 60 s" count={http?.requests} detail={`${value(api?.total?.requests)} desde el arranque`} /><Stat label="Peticiones en curso" count={api?.inflight} detail="Incluye esta consulta del panel" /><Stat label="Latencia media · ms" count={http?.avgMs} detail={`P95 aproximado: ${http?.p95Overflow ? '> 3000' : value(http?.p95Ms)} ms`} /><Stat label="Errores de servidor · 60 s" count={http?.errors5xx} detail={`${value(http?.errors4xx)} respuestas 4xx · ${value(http?.limited)} de ellas 429`} alert={http?.errors5xx > 0} /></div>
      <p className="mt-3 text-xs text-muted-foreground">Incluye supervisión y solicitudes rechazadas. Conexiones abandonadas en 60 s: {value(http?.aborted)}. Excluye rechazos previos en Traefik.</p>
      <Chart history={api?.history} lines={[{ key: 'requests', label: 'Peticiones', color: '#0891b2' }, { key: 'errors5xx', label: 'Errores 5xx', color: '#e11d48' }]} />
      {!!api?.routes?.length && <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><caption className="mb-2 text-left font-medium">Tráfico por servicio · desde el arranque</caption><thead className="text-muted-foreground"><tr>{['Servicio', 'Peticiones', '4xx', '5xx', '429', 'Media ms'].map((title) => <th key={title} className="border-b p-2">{title}</th>)}</tr></thead><tbody>{api.routes.map((route) => <tr key={route.family}><td className="p-2 font-medium">{route.family}</td>{['requests', 'errors4xx', 'errors5xx', 'limited', 'avgMs'].map((key) => <td className="p-2 tabular-nums" key={key}>{value(route[key])}</td>)}</tr>)}</tbody></table></div>}
      <p className="mt-3 text-xs text-muted-foreground">API HTTP de Moonbot (otro proceso): {value(telegram?.http)} peticiones / 60 s · {value(telegram?.http_errors)} errores.</p>
    </section>
    <div className="grid gap-5 lg:grid-cols-2"><section className="space-y-4 rounded-xl border p-4"><h3 className="font-semibold">Recursos y disponibilidad</h3><Usage label="CPU del entorno Moonbot" used={r?.cpu} note="Lectura psutil del entorno; no equivale a consumo de la cuota Docker." /><Usage label="Memoria del entorno" used={r?.ram} note={`${value(r?.ramUsedGb)} / ${value(r?.ramTotalGb)} GB`} /><Usage label="Disco del entorno" used={r?.disk} note="Volumen que ve Moonbot." /><div className="grid grid-cols-2 gap-3 text-xs"><p>Uptime: <b>{r?.uptime || '—'}</b></p><p>Versión: <b>{r?.version || '—'}</b></p><p>Reinicios Docker: <b>{value(node?.restarts)}</b></p><p>Última terminación por memoria: <b>{node?.oomKilled == null ? '—' : node.oomKilled ? 'Sí' : 'No'}</b></p></div></section>
      <section className="rounded-xl border p-4"><h3 className="font-semibold">Límites y capacidad</h3><dl className="mt-4 space-y-3 text-sm">{[
        ['Memoria Docker', node?.limits ? node.limits.memoryBytes ? `${value(node.limits.memoryBytes / 1024 ** 2)} MiB` : 'Sin límite explícito' : 'Sin datos'],
        ['Cuota CPU Docker', node?.limits ? node.limits.cpus ? `${value(node.limits.cpus)} CPU` : 'Sin cuota explícita' : 'Sin datos'],
        ['Procesos máximos Docker', node?.limits ? node.limits.pids ? value(node.limits.pids) : 'Sin límite explícito' : 'Sin datos'],
        ['Workers configurados / techo del código', `${value(data?.balancer?.plan?.max_workers)} / 32`], ['Cuerpo JSON API web', '6 MB por petición'], ['Contenedores', '1 activo / hasta 12 configurados'],
      ].map(([label, limit]) => <div key={label} className="flex justify-between gap-4 border-b pb-2"><dt className="text-muted-foreground">{label}</dt><dd className="text-right font-medium">{limit}</dd></div>)}</dl><div className="mt-4 rounded-lg bg-muted/30 p-3 text-xs"><b>Referencias de envío de Telegram</b><p className="mt-2">Evitar más de 1 mensaje/s en un chat; máximo 20 mensajes/min en un grupo; difusión gratuita de aproximadamente 30 mensajes/s. Son límites de envío, no de recepción ni de todas las llamadas API.</p><p className="mt-2">El 429 y su retry_after indican la espera real. Este panel informa; no cambia los límites ni habilita difusión de pago.</p><a className="mt-2 inline-block underline" href="https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this" target="_blank" rel="noreferrer">Límites oficiales de Telegram</a></div></section></div>
  </div>;
}
