import React, { useEffect, useState } from 'react';
import { Activity, AlertTriangle, DatabaseBackup, Gauge, RefreshCw, ServerCog, Wrench } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'; import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Badge } from '@/components/ui/badge';
import apiServerClient from '@/lib/apiServerClient'; import pb from '@/lib/pocketbaseClient';

const MoonbotOperationsCenter = ({ groups = [] }) => {
  const [data, setData] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [deploy, setDeploy] = useState({ version: '', instances: '', batch_size: 1 }); const [backup, setBackup] = useState({ retention_days: 30, modules: 'all' });
  const [restore, setRestore] = useState({ backup_id: '', modules: 'all' }); const [dependency, setDependency] = useState({ name: 'Telegram', status: 'ok', latency_ms: 0, detail: '' });
  const [maintenance, setMaintenance] = useState({ starts_at: '', ends_at: '', modules: 'api,worker', message: '' });
  const request = async (body) => { setBusy(true); setError(''); try { const response = await apiServerClient.fetch('/moonbot-admin/operations', { method: body ? 'POST' : 'GET', headers: { Authorization: `Bearer ${pb.authStore.token}`, ...(body ? { 'Content-Type': 'application/json' } : {}) }, body: body ? JSON.stringify(body) : undefined }); const payload = await response.json(); if (!response.ok || !payload.ok) throw new Error(payload.error || `HTTP ${response.status}`); if (!body) setData(payload); return payload; } catch (reason) { setError(reason.message); return null; } finally { setBusy(false); } };
  const mutate = async (body) => { if (await request(body)) await request(); }; useEffect(() => { request(); }, []);
  const metric = (label, value, suffix = '%') => <div className="rounded-xl border bg-muted/20 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="text-2xl font-bold">{value ?? '—'}{suffix}</p></div>;
  return <Card className="mt-8 border-emerald-500/20"><CardHeader><CardTitle className="flex items-center gap-2"><ServerCog className="h-5 w-5 text-emerald-600"/>Operaciones y fiabilidad Moonbot</CardTitle><CardDescription>Planifica cambios, detecta degradaciones y prepara recuperación sin ejecutar acciones destructivas automáticamente.</CardDescription></CardHeader><CardContent className="space-y-6">
    <div className="flex justify-end"><Button variant="outline" disabled={busy} onClick={() => request()}><RefreshCw className={`mr-2 h-4 w-4 ${busy ? 'animate-spin' : ''}`}/>Actualizar</Button></div>{error && <p className="rounded-lg bg-red-500/10 p-3 text-sm text-red-600">{error}</p>}
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{metric('CPU', data?.metrics?.cpu)}{metric('Memoria', data?.metrics?.memory)}{metric('Disco', data?.metrics?.disk)}{metric('Latencia', data?.metrics?.latency, ' ms')}</div>
    {(data?.alerts?.length > 0 || data?.degraded?.degraded) && <div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm"><p className="flex items-center gap-2 font-semibold"><AlertTriangle className="h-4 w-4"/>Atención operativa</p><p>{data.alerts?.map((x) => `${x.metric}: ${x.value}/${x.threshold}`).join(' · ')} {data.degraded?.failed?.length ? `Dependencias degradadas: ${data.degraded.failed.join(', ')}` : ''}</p></div>}
    <div className="grid gap-4 xl:grid-cols-2">
      <section className="space-y-3 rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><Activity className="h-4 w-4"/>Despliegue gradual</h3><Input placeholder="Versión" value={deploy.version} onChange={(e) => setDeploy({ ...deploy, version: e.target.value })}/><Input placeholder="Instancias separadas por comas" value={deploy.instances} onChange={(e) => setDeploy({ ...deploy, instances: e.target.value })}/><Input type="number" min="1" value={deploy.batch_size} onChange={(e) => setDeploy({ ...deploy, batch_size: e.target.value })}/><Button onClick={() => mutate({ action: 'deployment', ...deploy, instances: deploy.instances.split(',').map((x) => x.trim()).filter(Boolean) })}>Crear plan</Button></section>
      <section className="space-y-3 rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><DatabaseBackup className="h-4 w-4"/>Copias y restauración</h3><div className="grid grid-cols-2 gap-2"><Input type="number" min="1" value={backup.retention_days} onChange={(e) => setBackup({ ...backup, retention_days: e.target.value })}/><Input value={backup.modules} onChange={(e) => setBackup({ ...backup, modules: e.target.value })}/></div><Button onClick={() => mutate({ action: 'backup_policy', retention_days: backup.retention_days, encrypted: true, modules: backup.modules.split(',') })}>Guardar política cifrada</Button><div className="grid grid-cols-2 gap-2"><Input placeholder="ID de copia" value={restore.backup_id} onChange={(e) => setRestore({ ...restore, backup_id: e.target.value })}/><Input value={restore.modules} onChange={(e) => setRestore({ ...restore, modules: e.target.value })}/></div><Button variant="outline" onClick={() => mutate({ action: 'restore_plan', backup_id: restore.backup_id, groups: groups.map((x) => String(x.id || x.chat_id)), modules: restore.modules.split(',') })}>Preparar restauración</Button></section>
      <section className="space-y-3 rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><Gauge className="h-4 w-4"/>Dependencias y modo degradado</h3><div className="grid grid-cols-2 gap-2"><Input value={dependency.name} onChange={(e) => setDependency({ ...dependency, name: e.target.value })}/><select className="h-10 rounded-md border bg-background px-3" value={dependency.status} onChange={(e) => setDependency({ ...dependency, status: e.target.value })}><option value="ok">Correcta</option><option value="degraded">Degradada</option><option value="offline">Fuera de línea</option><option value="unknown">Desconocida</option></select></div><Input type="number" placeholder="Latencia ms" value={dependency.latency_ms} onChange={(e) => setDependency({ ...dependency, latency_ms: e.target.value })}/><Input placeholder="Detalle" value={dependency.detail} onChange={(e) => setDependency({ ...dependency, detail: e.target.value })}/><Button onClick={() => mutate({ action: 'dependency', ...dependency })}>Registrar comprobación</Button></section>
      <section className="space-y-3 rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><Wrench className="h-4 w-4"/>Ventana de mantenimiento</h3><div className="grid grid-cols-2 gap-2"><Input type="datetime-local" value={maintenance.starts_at} onChange={(e) => setMaintenance({ ...maintenance, starts_at: e.target.value })}/><Input type="datetime-local" value={maintenance.ends_at} onChange={(e) => setMaintenance({ ...maintenance, ends_at: e.target.value })}/></div><Input value={maintenance.modules} onChange={(e) => setMaintenance({ ...maintenance, modules: e.target.value })}/><Input placeholder="Mensaje público" value={maintenance.message} onChange={(e) => setMaintenance({ ...maintenance, message: e.target.value })}/><Button onClick={() => mutate({ action: 'maintenance', ...maintenance, modules: maintenance.modules.split(',') })}>Programar mantenimiento</Button></section>
    </div>
    <section className="rounded-xl border p-4"><h3 className="mb-2 font-semibold">Diagnóstico automático</h3><p className="text-sm">Estado: <Badge>{data?.diagnosis?.health || '—'}</Badge></p><ul className="mt-2 list-disc pl-5 text-sm text-muted-foreground">{data?.diagnosis?.recommendations?.map((item) => <li key={item}>{item}</li>)}</ul><p className="mt-2 text-xs text-muted-foreground">{data?.error_groups?.length || 0} grupos de errores · moderación disponible: {data?.degraded?.capabilities?.moderation ? 'sí' : 'no'}</p></section>
    <section className="rounded-xl border p-4"><h3 className="mb-2 font-semibold">Planes pendientes</h3><div className="space-y-2">{data?.deployments?.slice(0, 5).map((item) => { const instance = item.instances?.find((x) => !item.completed?.includes(x) && !item.failed?.includes(x)); return <div key={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-muted/30 p-3 text-sm"><span>Despliegue {item.version} · {item.status} · lote {item.batch_size}</span>{instance && <span className="space-x-2"><Button size="sm" variant="outline" onClick={() => mutate({ action: 'health_result', deployment_id: item.id, instance, healthy: true })}>{instance} correcta</Button><Button size="sm" variant="destructive" onClick={() => mutate({ action: 'health_result', deployment_id: item.id, instance, healthy: false })}>Fallo</Button></span>}</div>; })}{data?.restore_plans?.filter((x) => x.status === 'pending_confirmation').map((item) => <div key={item.id} className="flex items-center justify-between rounded-lg bg-muted/30 p-3 text-sm"><span>Restauración {item.backup_id} · pendiente de confirmación</span><Button size="sm" variant="destructive" onClick={() => mutate({ action: 'restore_cancel', plan_id: item.id })}>Cancelar</Button></div>)}{data?.maintenance?.filter((x) => x.status === 'scheduled').map((item) => <div key={item.id} className="flex items-center justify-between rounded-lg bg-muted/30 p-3 text-sm"><span>Mantenimiento {item.starts_at} → {item.ends_at}</span><Button size="sm" variant="destructive" onClick={() => mutate({ action: 'maintenance_cancel', window_id: item.id })}>Cancelar</Button></div>)}</div></section>
  </CardContent></Card>;
}; export default MoonbotOperationsCenter;
