import { useEffect, useState } from 'react';
import apiServerClient from '@/lib/apiServerClient';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

export const parseNewsBlocks = (value) => { try { const result = typeof value === 'string' ? JSON.parse(value || '[]') : value; return Array.isArray(result) ? result.slice(0, 50).filter((item) => item && typeof item === 'object') : []; } catch { return []; } };
const id = () => globalThis.crypto?.randomUUID?.() || `block-${Date.now()}-${Math.random().toString(36).slice(2)}`;

function Preview({ content, blocks }) {
  const paragraphs = String(content || '').split(/\n\s*\n/).filter(Boolean);
  return <div className="space-y-3 rounded-lg border bg-white p-4 text-slate-900">{blocks.filter((b) => Number(b.position) === 0).map((b) => <Block key={b.id} block={b}/>)}{paragraphs.map((text, index) => <div key={index}><p className="whitespace-pre-wrap">{text}</p>{blocks.filter((b) => Number(b.position) === index + 1).map((b) => <Block key={b.id} block={b}/>)}</div>)}</div>;
}
function Block({ block }) { if (block.type === 'divider') return <hr className="my-4"/>; return <aside className="my-3 rounded-lg border-l-4 p-3" style={{ borderColor: block.accent || '#1982d1', background: `${block.accent || '#1982d1'}12` }}><small className="block uppercase opacity-60">{block.type.replace('_', ' ')}</small><b>{block.title || 'Bloque'}</b>{block.description && <p className="text-sm opacity-80">{block.description}</p>}{block.url && <span className="text-sm font-semibold" style={{ color: block.accent }}>{block.label || 'Abrir'} →</span>}</aside>; }

export default function NewsLayoutBlocksEditor({ value, onChange, content }) {
  const blocks = parseNewsBlocks(value); const [sources, setSources] = useState([]); const [ads, setAds] = useState([]); const [rss, setRss] = useState([]); const paragraphCount = Math.max(1, String(content || '').split(/\n\s*\n/).filter(Boolean).length);
  useEffect(() => { Promise.all([apiServerClient.fetch('/noticias/recommended').then((r) => r.json()), apiServerClient.fetch('/house-ads?site=noticiasweb3').then((r) => r.json()), apiServerClient.fetch('/noticias/recommended/rss-blocks').then((r) => r.json())]).then(([recommended, campaigns, feeds]) => { setSources(recommended.items || []); setAds(campaigns.ads || []); setRss(feeds.items || []); }).catch(() => {}); }, []);
  const add = (type, source = {}) => { if (blocks.length >= 50) return; onChange([...blocks, { id: id(), type, position: paragraphCount, source_id: source.id || '', title: source.title || '', description: source.description || '', url: source.url || '', label: source.label || source.cta || 'Abrir', accent: source.accent || '#1982d1' }]); };
  const update = (blockId, changes) => onChange(blocks.map((block) => block.id === blockId ? { ...block, ...changes } : block));
  const move = (from, to) => { const next = [...blocks]; const [item] = next.splice(from, 1); next.splice(to, 0, item); onChange(next); };
  return <div className="space-y-3 rounded-xl border bg-muted/20 p-4"><div><b>Editor visual de legos</b><p className="text-xs text-muted-foreground">Arrastra para ordenar y elige la posición dentro del texto.</p></div><div className="flex flex-wrap gap-2">{[['recommended','Recomendado'],['community_ad','Campaña'],['affiliate','Afiliado'],['callout','Recuadro'],['divider','Separador']].map(([type,label]) => <Button key={type} type="button" size="sm" variant="outline" onClick={() => add(type)}>+ {label}</Button>)}</div>
    {(sources.length > 0 || ads.length > 0 || rss.length > 0) && <div className="grid gap-2 md:grid-cols-3"><select className="h-9 rounded-md border bg-background px-2 text-xs" defaultValue="" onChange={(e) => { const source = sources.find((item) => item.id === e.target.value); if (source) add('recommended', source); e.target.value=''; }}><option value="">Añadir parte de la web…</option>{sources.map((source) => <option key={source.id} value={source.id}>{source.title}</option>)}</select><select className="h-9 rounded-md border bg-background px-2 text-xs" defaultValue="" onChange={(e) => { const source = ads.find((item) => item.id === e.target.value); if (source) add('community_ad', source); e.target.value=''; }}><option value="">Añadir campaña aprobada…</option>{ads.map((source) => <option key={source.id} value={source.id}>{source.title}</option>)}</select><select className="h-9 rounded-md border bg-background px-2 text-xs" defaultValue="" onChange={(e) => { const source = rss.find((item) => item.id === e.target.value); if (source) add('rss', source); e.target.value=''; }}><option value="">Añadir RSS de Moonbot…</option>{rss.map((source) => <option key={source.id} value={source.id}>{source.title}</option>)}</select></div>}
    <div className="space-y-2">{blocks.map((block, index) => <div key={block.id} draggable onDragStart={(e) => e.dataTransfer.setData('text/block-index', String(index))} onDragOver={(e) => e.preventDefault()} onDrop={(e) => move(Number(e.dataTransfer.getData('text/block-index')), index)} className="space-y-2 rounded-lg border bg-background p-3"><div className="flex justify-between"><b className="text-xs">⠿ {block.type}</b><button type="button" className="text-xs text-destructive" onClick={() => onChange(blocks.filter((item) => item.id !== block.id))}>Eliminar</button></div>{block.type !== 'divider' && <><Input value={block.title || ''} onChange={(e) => update(block.id,{title:e.target.value})} placeholder="Título"/><Input value={block.url || ''} onChange={(e) => update(block.id,{url:e.target.value})} placeholder="URL"/></>}<select className="h-9 w-full rounded-md border bg-background px-2 text-xs" value={block.position} onChange={(e) => update(block.id,{position:Number(e.target.value)})}>{Array.from({length:paragraphCount+1},(_,p)=><option key={p} value={p}>{p===0?'Antes del texto':p===paragraphCount?'Al final':`Después del párrafo ${p}`}</option>)}</select></div>)}</div>
    <details><summary className="cursor-pointer text-sm font-semibold">Vista previa del artículo</summary><div className="mt-3"><Preview content={content} blocks={blocks}/></div></details></div>;
}
