import { useEffect, useMemo, useRef, useState } from 'react';
import { Button } from '@/components/ui/button';

const wrap = (text,start,end,before,after=before)=>`${text.slice(0,start)}${before}${text.slice(start,end)||'texto'}${after}${text.slice(end)}`;
const prefix = (text,start,end,value)=>`${text.slice(0,start)}${text.slice(start,end).split('\n').map((line)=>value+line).join('\n')}${text.slice(end)}`;
export default function RichNewsTextEditor({ value, onChange, draftKey }) {
  const ref=useRef(null); const [preview,setPreview]=useState(false); const [mobile,setMobile]=useState(false); const [saved,setSaved]=useState(''); const words=useMemo(()=>String(value).trim().split(/\s+/).filter(Boolean).length,[value]);
  useEffect(()=>{const timer=setTimeout(()=>{try{localStorage.setItem(`tsa-nw3-draft:${draftKey}`,value);setSaved(new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}));}catch{}},800);return()=>clearTimeout(timer);},[value,draftKey]);
  const format=(kind)=>{const input=ref.current,start=input.selectionStart,end=input.selectionEnd;let next=value;if(kind==='bold')next=wrap(value,start,end,'**');if(kind==='italic')next=wrap(value,start,end,'*');if(kind==='underline')next=wrap(value,start,end,'<u>','</u>');if(kind==='h1')next=prefix(value,start,end,'# ');if(kind==='h2')next=prefix(value,start,end,'## ');if(kind==='ul')next=prefix(value,start,end,'- ');if(kind==='quote')next=prefix(value,start,end,'> ');if(kind==='link'){const url=prompt('Enlace HTTPS');if(url?.startsWith('https://'))next=wrap(value,start,end,'[',`](${url})`);}onChange(next);requestAnimationFrame(()=>input.focus());};
  return <div className="overflow-hidden rounded-xl border bg-background"><div className="flex flex-wrap gap-1 border-b bg-muted/50 p-2">{[['h1','Título'],['h2','Subtítulo'],['bold','B'],['italic','I'],['underline','U'],['ul','• Lista'],['quote','❝'],['link','🔗']].map(([kind,label])=><Button key={kind} type="button" size="sm" variant="ghost" onClick={()=>format(kind)}>{label}</Button>)}<span className="flex-1"/><Button type="button" size="sm" variant={mobile?'default':'outline'} onClick={()=>setMobile(!mobile)}>{mobile?'Móvil':'Escritorio'}</Button><Button type="button" size="sm" variant={preview?'default':'outline'} onClick={()=>setPreview(!preview)}>Vista previa</Button></div>{preview?<div className={`mx-auto min-h-72 bg-white p-8 font-serif leading-7 text-slate-900 shadow-sm ${mobile?'max-w-sm':'max-w-3xl'}`}>{String(value).split(/\n\s*\n/).filter(Boolean).map((text,index)=><p className="mb-4 whitespace-pre-wrap" key={index}>{text}</p>)}</div>:<textarea ref={ref} className="min-h-80 w-full resize-y bg-white p-8 font-serif leading-7 text-slate-900 outline-none" value={value} onChange={(event)=>onChange(event.target.value)} spellCheck="true"/>}<div className="flex justify-between border-t bg-muted/30 px-3 py-1 text-xs text-muted-foreground"><span>{words} palabras · {Math.max(1,Math.ceil(words/220))} min</span><span>{saved?`Autoguardado ${saved}`:'Autoguardado activo'}</span></div></div>;
}
